// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform.proto

package platformv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	platformv1 "ebof-wg-mesh/api/proto/platformv1"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

const _ = connect.IsAtLeastVersion1_13_0

const (
	PlatformServiceName = "platform.v1.PlatformService"
	BuilderServiceName  = "platform.v1.BuilderService"
	OpsServiceName      = "platform.v1.OpsService"
)

const (
	PlatformServiceCreateProjectProcedure          = "/platform.v1.PlatformService/CreateProject"
	PlatformServiceListProjectsProcedure           = "/platform.v1.PlatformService/ListProjects"
	PlatformServiceGetProjectProcedure             = "/platform.v1.PlatformService/GetProject"
	PlatformServiceListEnvironmentsProcedure       = "/platform.v1.PlatformService/ListEnvironments"
	PlatformServiceGetEnvironmentProcedure         = "/platform.v1.PlatformService/GetEnvironment"
	PlatformServiceCreateEnvironmentProcedure      = "/platform.v1.PlatformService/CreateEnvironment"
	PlatformServiceDuplicateEnvironmentProcedure   = "/platform.v1.PlatformService/DuplicateEnvironment"
	PlatformServiceRenameEnvironmentProcedure      = "/platform.v1.PlatformService/RenameEnvironment"
	PlatformServiceDeleteEnvironmentProcedure      = "/platform.v1.PlatformService/DeleteEnvironment"
	PlatformServiceReleaseEnvironmentProcedure     = "/platform.v1.PlatformService/ReleaseEnvironment"
	PlatformServiceLinkGitHubRepositoryProcedure   = "/platform.v1.PlatformService/LinkGitHubRepository"
	PlatformServiceInspectSourceProcedure          = "/platform.v1.PlatformService/InspectSource"
	PlatformServiceCreateServiceProcedure          = "/platform.v1.PlatformService/CreateService"
	PlatformServiceUpdateServiceProcedure          = "/platform.v1.PlatformService/UpdateService"
	PlatformServiceScaleServiceProcedure           = "/platform.v1.PlatformService/ScaleService"
	PlatformServiceApplyDeploymentActionProcedure  = "/platform.v1.PlatformService/ApplyDeploymentAction"
	PlatformServiceDiscardServiceChangesProcedure  = "/platform.v1.PlatformService/DiscardServiceChanges"
	PlatformServiceDeleteServiceProcedure          = "/platform.v1.PlatformService/DeleteService"
	PlatformServiceGetServiceProcedure             = "/platform.v1.PlatformService/GetService"
	PlatformServiceListServicesProcedure           = "/platform.v1.PlatformService/ListServices"
	PlatformServiceCreateVolumeProcedure           = "/platform.v1.PlatformService/CreateVolume"
	PlatformServiceDeleteVolumeProcedure           = "/platform.v1.PlatformService/DeleteVolume"
	PlatformServiceListVolumesProcedure            = "/platform.v1.PlatformService/ListVolumes"
	PlatformServiceCreateDomainBindingProcedure    = "/platform.v1.PlatformService/CreateDomainBinding"
	PlatformServiceGenerateDomainBindingProcedure  = "/platform.v1.PlatformService/GenerateDomainBinding"
	PlatformServiceGetDomainBindingProcedure       = "/platform.v1.PlatformService/GetDomainBinding"
	PlatformServiceListDomainBindingsProcedure     = "/platform.v1.PlatformService/ListDomainBindings"
	PlatformServiceUpdateDomainBindingProcedure    = "/platform.v1.PlatformService/UpdateDomainBinding"
	PlatformServiceDeleteDomainBindingProcedure    = "/platform.v1.PlatformService/DeleteDomainBinding"
	PlatformServiceGetServiceStatusProcedure       = "/platform.v1.PlatformService/GetServiceStatus"
	PlatformServiceListServiceLogsProcedure        = "/platform.v1.PlatformService/ListServiceLogs"
	PlatformServiceListServiceDeploymentsProcedure = "/platform.v1.PlatformService/ListServiceDeployments"
	PlatformServiceListAgentsProcedure             = "/platform.v1.PlatformService/ListAgents"
	BuilderServiceClaimBuildProcedure              = "/platform.v1.BuilderService/ClaimBuild"
	BuilderServiceDownloadSourceSnapshotProcedure  = "/platform.v1.BuilderService/DownloadSourceSnapshot"
	BuilderServiceReportBuildHeartbeatProcedure    = "/platform.v1.BuilderService/ReportBuildHeartbeat"
	BuilderServiceReportBuildLogsProcedure         = "/platform.v1.BuilderService/ReportBuildLogs"
	BuilderServiceCompleteBuildProcedure           = "/platform.v1.BuilderService/CompleteBuild"
	OpsServiceIngestGitHubWebhookProcedure         = "/platform.v1.OpsService/IngestGitHubWebhook"
	OpsServiceListFleetProcedure                   = "/platform.v1.OpsService/ListFleet"
	OpsServiceCreateAgentProcedure                 = "/platform.v1.OpsService/CreateAgent"
	OpsServiceUpdateAgentProcedure                 = "/platform.v1.OpsService/UpdateAgent"
	OpsServiceSetAgentLifecycleProcedure           = "/platform.v1.OpsService/SetAgentLifecycle"
)

type PlatformServiceClient interface {
	CreateProject(context.Context, *connect.Request[platformv1.CreateProjectRequest]) (*connect.Response[platformv1.Project], error)
	ListProjects(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.ListProjectsResponse], error)
	GetProject(context.Context, *connect.Request[platformv1.GetProjectRequest]) (*connect.Response[platformv1.Project], error)
	ListEnvironments(context.Context, *connect.Request[platformv1.ListEnvironmentsRequest]) (*connect.Response[platformv1.ListEnvironmentsResponse], error)
	GetEnvironment(context.Context, *connect.Request[platformv1.GetEnvironmentRequest]) (*connect.Response[platformv1.Environment], error)
	CreateEnvironment(context.Context, *connect.Request[platformv1.CreateEnvironmentRequest]) (*connect.Response[platformv1.Environment], error)
	DuplicateEnvironment(context.Context, *connect.Request[platformv1.DuplicateEnvironmentRequest]) (*connect.Response[platformv1.Environment], error)
	RenameEnvironment(context.Context, *connect.Request[platformv1.RenameEnvironmentRequest]) (*connect.Response[platformv1.Environment], error)
	DeleteEnvironment(context.Context, *connect.Request[platformv1.DeleteEnvironmentRequest]) (*connect.Response[emptypb.Empty], error)
	ReleaseEnvironment(context.Context, *connect.Request[platformv1.ReleaseEnvironmentRequest]) (*connect.Response[platformv1.ReleaseEnvironmentResponse], error)
	LinkGitHubRepository(context.Context, *connect.Request[platformv1.LinkGitHubRepositoryRequest]) (*connect.Response[platformv1.InspectSourceResponse], error)
	InspectSource(context.Context, *connect.Request[platformv1.InspectSourceRequest]) (*connect.Response[platformv1.InspectSourceResponse], error)
	CreateService(context.Context, *connect.Request[platformv1.CreateServiceRequest]) (*connect.Response[platformv1.Service], error)
	UpdateService(context.Context, *connect.Request[platformv1.UpdateServiceRequest]) (*connect.Response[platformv1.Service], error)
	ScaleService(context.Context, *connect.Request[platformv1.ScaleServiceRequest]) (*connect.Response[platformv1.ServiceStatus], error)
	ApplyDeploymentAction(context.Context, *connect.Request[platformv1.ApplyDeploymentActionRequest]) (*connect.Response[platformv1.ServiceStatus], error)
	DiscardServiceChanges(context.Context, *connect.Request[platformv1.DiscardServiceChangesRequest]) (*connect.Response[platformv1.Service], error)
	DeleteService(context.Context, *connect.Request[platformv1.DeleteServiceRequest]) (*connect.Response[emptypb.Empty], error)
	GetService(context.Context, *connect.Request[platformv1.GetServiceRequest]) (*connect.Response[platformv1.Service], error)
	ListServices(context.Context, *connect.Request[platformv1.ListServicesRequest]) (*connect.Response[platformv1.ListServicesResponse], error)
	CreateVolume(context.Context, *connect.Request[platformv1.CreateVolumeRequest]) (*connect.Response[platformv1.Volume], error)
	DeleteVolume(context.Context, *connect.Request[platformv1.DeleteVolumeRequest]) (*connect.Response[emptypb.Empty], error)
	ListVolumes(context.Context, *connect.Request[platformv1.ListVolumesRequest]) (*connect.Response[platformv1.ListVolumesResponse], error)
	CreateDomainBinding(context.Context, *connect.Request[platformv1.CreateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error)
	GenerateDomainBinding(context.Context, *connect.Request[platformv1.GenerateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error)
	GetDomainBinding(context.Context, *connect.Request[platformv1.GetDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error)
	ListDomainBindings(context.Context, *connect.Request[platformv1.ListDomainBindingsRequest]) (*connect.Response[platformv1.ListDomainBindingsResponse], error)
	UpdateDomainBinding(context.Context, *connect.Request[platformv1.UpdateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error)
	DeleteDomainBinding(context.Context, *connect.Request[platformv1.DeleteDomainBindingRequest]) (*connect.Response[emptypb.Empty], error)
	GetServiceStatus(context.Context, *connect.Request[platformv1.GetServiceStatusRequest]) (*connect.Response[platformv1.ServiceStatus], error)
	ListServiceLogs(context.Context, *connect.Request[platformv1.ListServiceLogsRequest]) (*connect.Response[platformv1.ListServiceLogsResponse], error)
	ListServiceDeployments(context.Context, *connect.Request[platformv1.ListServiceDeploymentsRequest]) (*connect.Response[platformv1.ListServiceDeploymentsResponse], error)
	ListAgents(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.ListAgentsResponse], error)
}

func NewPlatformServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PlatformServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	platformServiceMethods := platformv1.File_platform_proto.Services().ByName("PlatformService").Methods()
	return &platformServiceClient{
		createProject: connect.NewClient[platformv1.CreateProjectRequest, platformv1.Project](
			httpClient,
			baseURL+PlatformServiceCreateProjectProcedure,
			connect.WithSchema(platformServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[emptypb.Empty, platformv1.ListProjectsResponse](
			httpClient,
			baseURL+PlatformServiceListProjectsProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		getProject: connect.NewClient[platformv1.GetProjectRequest, platformv1.Project](
			httpClient,
			baseURL+PlatformServiceGetProjectProcedure,
			connect.WithSchema(platformServiceMethods.ByName("GetProject")),
			connect.WithClientOptions(opts...),
		),
		listEnvironments: connect.NewClient[platformv1.ListEnvironmentsRequest, platformv1.ListEnvironmentsResponse](
			httpClient,
			baseURL+PlatformServiceListEnvironmentsProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ListEnvironments")),
			connect.WithClientOptions(opts...),
		),
		getEnvironment: connect.NewClient[platformv1.GetEnvironmentRequest, platformv1.Environment](
			httpClient,
			baseURL+PlatformServiceGetEnvironmentProcedure,
			connect.WithSchema(platformServiceMethods.ByName("GetEnvironment")),
			connect.WithClientOptions(opts...),
		),
		createEnvironment: connect.NewClient[platformv1.CreateEnvironmentRequest, platformv1.Environment](
			httpClient,
			baseURL+PlatformServiceCreateEnvironmentProcedure,
			connect.WithSchema(platformServiceMethods.ByName("CreateEnvironment")),
			connect.WithClientOptions(opts...),
		),
		duplicateEnvironment: connect.NewClient[platformv1.DuplicateEnvironmentRequest, platformv1.Environment](
			httpClient,
			baseURL+PlatformServiceDuplicateEnvironmentProcedure,
			connect.WithSchema(platformServiceMethods.ByName("DuplicateEnvironment")),
			connect.WithClientOptions(opts...),
		),
		renameEnvironment: connect.NewClient[platformv1.RenameEnvironmentRequest, platformv1.Environment](
			httpClient,
			baseURL+PlatformServiceRenameEnvironmentProcedure,
			connect.WithSchema(platformServiceMethods.ByName("RenameEnvironment")),
			connect.WithClientOptions(opts...),
		),
		deleteEnvironment: connect.NewClient[platformv1.DeleteEnvironmentRequest, emptypb.Empty](
			httpClient,
			baseURL+PlatformServiceDeleteEnvironmentProcedure,
			connect.WithSchema(platformServiceMethods.ByName("DeleteEnvironment")),
			connect.WithClientOptions(opts...),
		),
		releaseEnvironment: connect.NewClient[platformv1.ReleaseEnvironmentRequest, platformv1.ReleaseEnvironmentResponse](
			httpClient,
			baseURL+PlatformServiceReleaseEnvironmentProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ReleaseEnvironment")),
			connect.WithClientOptions(opts...),
		),
		linkGitHubRepository: connect.NewClient[platformv1.LinkGitHubRepositoryRequest, platformv1.InspectSourceResponse](
			httpClient,
			baseURL+PlatformServiceLinkGitHubRepositoryProcedure,
			connect.WithSchema(platformServiceMethods.ByName("LinkGitHubRepository")),
			connect.WithClientOptions(opts...),
		),
		inspectSource: connect.NewClient[platformv1.InspectSourceRequest, platformv1.InspectSourceResponse](
			httpClient,
			baseURL+PlatformServiceInspectSourceProcedure,
			connect.WithSchema(platformServiceMethods.ByName("InspectSource")),
			connect.WithClientOptions(opts...),
		),
		createService: connect.NewClient[platformv1.CreateServiceRequest, platformv1.Service](
			httpClient,
			baseURL+PlatformServiceCreateServiceProcedure,
			connect.WithSchema(platformServiceMethods.ByName("CreateService")),
			connect.WithClientOptions(opts...),
		),
		updateService: connect.NewClient[platformv1.UpdateServiceRequest, platformv1.Service](
			httpClient,
			baseURL+PlatformServiceUpdateServiceProcedure,
			connect.WithSchema(platformServiceMethods.ByName("UpdateService")),
			connect.WithClientOptions(opts...),
		),
		scaleService: connect.NewClient[platformv1.ScaleServiceRequest, platformv1.ServiceStatus](
			httpClient,
			baseURL+PlatformServiceScaleServiceProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ScaleService")),
			connect.WithClientOptions(opts...),
		),
		applyDeploymentAction: connect.NewClient[platformv1.ApplyDeploymentActionRequest, platformv1.ServiceStatus](
			httpClient,
			baseURL+PlatformServiceApplyDeploymentActionProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ApplyDeploymentAction")),
			connect.WithClientOptions(opts...),
		),
		discardServiceChanges: connect.NewClient[platformv1.DiscardServiceChangesRequest, platformv1.Service](
			httpClient,
			baseURL+PlatformServiceDiscardServiceChangesProcedure,
			connect.WithSchema(platformServiceMethods.ByName("DiscardServiceChanges")),
			connect.WithClientOptions(opts...),
		),
		deleteService: connect.NewClient[platformv1.DeleteServiceRequest, emptypb.Empty](
			httpClient,
			baseURL+PlatformServiceDeleteServiceProcedure,
			connect.WithSchema(platformServiceMethods.ByName("DeleteService")),
			connect.WithClientOptions(opts...),
		),
		getService: connect.NewClient[platformv1.GetServiceRequest, platformv1.Service](
			httpClient,
			baseURL+PlatformServiceGetServiceProcedure,
			connect.WithSchema(platformServiceMethods.ByName("GetService")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[platformv1.ListServicesRequest, platformv1.ListServicesResponse](
			httpClient,
			baseURL+PlatformServiceListServicesProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		createVolume: connect.NewClient[platformv1.CreateVolumeRequest, platformv1.Volume](
			httpClient,
			baseURL+PlatformServiceCreateVolumeProcedure,
			connect.WithSchema(platformServiceMethods.ByName("CreateVolume")),
			connect.WithClientOptions(opts...),
		),
		deleteVolume: connect.NewClient[platformv1.DeleteVolumeRequest, emptypb.Empty](
			httpClient,
			baseURL+PlatformServiceDeleteVolumeProcedure,
			connect.WithSchema(platformServiceMethods.ByName("DeleteVolume")),
			connect.WithClientOptions(opts...),
		),
		listVolumes: connect.NewClient[platformv1.ListVolumesRequest, platformv1.ListVolumesResponse](
			httpClient,
			baseURL+PlatformServiceListVolumesProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ListVolumes")),
			connect.WithClientOptions(opts...),
		),
		createDomainBinding: connect.NewClient[platformv1.CreateDomainBindingRequest, platformv1.DomainBinding](
			httpClient,
			baseURL+PlatformServiceCreateDomainBindingProcedure,
			connect.WithSchema(platformServiceMethods.ByName("CreateDomainBinding")),
			connect.WithClientOptions(opts...),
		),
		generateDomainBinding: connect.NewClient[platformv1.GenerateDomainBindingRequest, platformv1.DomainBinding](
			httpClient,
			baseURL+PlatformServiceGenerateDomainBindingProcedure,
			connect.WithSchema(platformServiceMethods.ByName("GenerateDomainBinding")),
			connect.WithClientOptions(opts...),
		),
		getDomainBinding: connect.NewClient[platformv1.GetDomainBindingRequest, platformv1.DomainBinding](
			httpClient,
			baseURL+PlatformServiceGetDomainBindingProcedure,
			connect.WithSchema(platformServiceMethods.ByName("GetDomainBinding")),
			connect.WithClientOptions(opts...),
		),
		listDomainBindings: connect.NewClient[platformv1.ListDomainBindingsRequest, platformv1.ListDomainBindingsResponse](
			httpClient,
			baseURL+PlatformServiceListDomainBindingsProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ListDomainBindings")),
			connect.WithClientOptions(opts...),
		),
		updateDomainBinding: connect.NewClient[platformv1.UpdateDomainBindingRequest, platformv1.DomainBinding](
			httpClient,
			baseURL+PlatformServiceUpdateDomainBindingProcedure,
			connect.WithSchema(platformServiceMethods.ByName("UpdateDomainBinding")),
			connect.WithClientOptions(opts...),
		),
		deleteDomainBinding: connect.NewClient[platformv1.DeleteDomainBindingRequest, emptypb.Empty](
			httpClient,
			baseURL+PlatformServiceDeleteDomainBindingProcedure,
			connect.WithSchema(platformServiceMethods.ByName("DeleteDomainBinding")),
			connect.WithClientOptions(opts...),
		),
		getServiceStatus: connect.NewClient[platformv1.GetServiceStatusRequest, platformv1.ServiceStatus](
			httpClient,
			baseURL+PlatformServiceGetServiceStatusProcedure,
			connect.WithSchema(platformServiceMethods.ByName("GetServiceStatus")),
			connect.WithClientOptions(opts...),
		),
		listServiceLogs: connect.NewClient[platformv1.ListServiceLogsRequest, platformv1.ListServiceLogsResponse](
			httpClient,
			baseURL+PlatformServiceListServiceLogsProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ListServiceLogs")),
			connect.WithClientOptions(opts...),
		),
		listServiceDeployments: connect.NewClient[platformv1.ListServiceDeploymentsRequest, platformv1.ListServiceDeploymentsResponse](
			httpClient,
			baseURL+PlatformServiceListServiceDeploymentsProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ListServiceDeployments")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[emptypb.Empty, platformv1.ListAgentsResponse](
			httpClient,
			baseURL+PlatformServiceListAgentsProcedure,
			connect.WithSchema(platformServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
	}
}

type platformServiceClient struct {
	createProject          *connect.Client[platformv1.CreateProjectRequest, platformv1.Project]
	listProjects           *connect.Client[emptypb.Empty, platformv1.ListProjectsResponse]
	getProject             *connect.Client[platformv1.GetProjectRequest, platformv1.Project]
	listEnvironments       *connect.Client[platformv1.ListEnvironmentsRequest, platformv1.ListEnvironmentsResponse]
	getEnvironment         *connect.Client[platformv1.GetEnvironmentRequest, platformv1.Environment]
	createEnvironment      *connect.Client[platformv1.CreateEnvironmentRequest, platformv1.Environment]
	duplicateEnvironment   *connect.Client[platformv1.DuplicateEnvironmentRequest, platformv1.Environment]
	renameEnvironment      *connect.Client[platformv1.RenameEnvironmentRequest, platformv1.Environment]
	deleteEnvironment      *connect.Client[platformv1.DeleteEnvironmentRequest, emptypb.Empty]
	releaseEnvironment     *connect.Client[platformv1.ReleaseEnvironmentRequest, platformv1.ReleaseEnvironmentResponse]
	linkGitHubRepository   *connect.Client[platformv1.LinkGitHubRepositoryRequest, platformv1.InspectSourceResponse]
	inspectSource          *connect.Client[platformv1.InspectSourceRequest, platformv1.InspectSourceResponse]
	createService          *connect.Client[platformv1.CreateServiceRequest, platformv1.Service]
	updateService          *connect.Client[platformv1.UpdateServiceRequest, platformv1.Service]
	scaleService           *connect.Client[platformv1.ScaleServiceRequest, platformv1.ServiceStatus]
	applyDeploymentAction  *connect.Client[platformv1.ApplyDeploymentActionRequest, platformv1.ServiceStatus]
	discardServiceChanges  *connect.Client[platformv1.DiscardServiceChangesRequest, platformv1.Service]
	deleteService          *connect.Client[platformv1.DeleteServiceRequest, emptypb.Empty]
	getService             *connect.Client[platformv1.GetServiceRequest, platformv1.Service]
	listServices           *connect.Client[platformv1.ListServicesRequest, platformv1.ListServicesResponse]
	createVolume           *connect.Client[platformv1.CreateVolumeRequest, platformv1.Volume]
	deleteVolume           *connect.Client[platformv1.DeleteVolumeRequest, emptypb.Empty]
	listVolumes            *connect.Client[platformv1.ListVolumesRequest, platformv1.ListVolumesResponse]
	createDomainBinding    *connect.Client[platformv1.CreateDomainBindingRequest, platformv1.DomainBinding]
	generateDomainBinding  *connect.Client[platformv1.GenerateDomainBindingRequest, platformv1.DomainBinding]
	getDomainBinding       *connect.Client[platformv1.GetDomainBindingRequest, platformv1.DomainBinding]
	listDomainBindings     *connect.Client[platformv1.ListDomainBindingsRequest, platformv1.ListDomainBindingsResponse]
	updateDomainBinding    *connect.Client[platformv1.UpdateDomainBindingRequest, platformv1.DomainBinding]
	deleteDomainBinding    *connect.Client[platformv1.DeleteDomainBindingRequest, emptypb.Empty]
	getServiceStatus       *connect.Client[platformv1.GetServiceStatusRequest, platformv1.ServiceStatus]
	listServiceLogs        *connect.Client[platformv1.ListServiceLogsRequest, platformv1.ListServiceLogsResponse]
	listServiceDeployments *connect.Client[platformv1.ListServiceDeploymentsRequest, platformv1.ListServiceDeploymentsResponse]
	listAgents             *connect.Client[emptypb.Empty, platformv1.ListAgentsResponse]
}

func (c *platformServiceClient) CreateProject(ctx context.Context, req *connect.Request[platformv1.CreateProjectRequest]) (*connect.Response[platformv1.Project], error) {
	return c.createProject.CallUnary(ctx, req)
}

func (c *platformServiceClient) ListProjects(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

func (c *platformServiceClient) GetProject(ctx context.Context, req *connect.Request[platformv1.GetProjectRequest]) (*connect.Response[platformv1.Project], error) {
	return c.getProject.CallUnary(ctx, req)
}

func (c *platformServiceClient) ListEnvironments(ctx context.Context, req *connect.Request[platformv1.ListEnvironmentsRequest]) (*connect.Response[platformv1.ListEnvironmentsResponse], error) {
	return c.listEnvironments.CallUnary(ctx, req)
}

func (c *platformServiceClient) GetEnvironment(ctx context.Context, req *connect.Request[platformv1.GetEnvironmentRequest]) (*connect.Response[platformv1.Environment], error) {
	return c.getEnvironment.CallUnary(ctx, req)
}

func (c *platformServiceClient) CreateEnvironment(ctx context.Context, req *connect.Request[platformv1.CreateEnvironmentRequest]) (*connect.Response[platformv1.Environment], error) {
	return c.createEnvironment.CallUnary(ctx, req)
}

func (c *platformServiceClient) DuplicateEnvironment(ctx context.Context, req *connect.Request[platformv1.DuplicateEnvironmentRequest]) (*connect.Response[platformv1.Environment], error) {
	return c.duplicateEnvironment.CallUnary(ctx, req)
}

func (c *platformServiceClient) RenameEnvironment(ctx context.Context, req *connect.Request[platformv1.RenameEnvironmentRequest]) (*connect.Response[platformv1.Environment], error) {
	return c.renameEnvironment.CallUnary(ctx, req)
}

func (c *platformServiceClient) DeleteEnvironment(ctx context.Context, req *connect.Request[platformv1.DeleteEnvironmentRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteEnvironment.CallUnary(ctx, req)
}

func (c *platformServiceClient) ReleaseEnvironment(ctx context.Context, req *connect.Request[platformv1.ReleaseEnvironmentRequest]) (*connect.Response[platformv1.ReleaseEnvironmentResponse], error) {
	return c.releaseEnvironment.CallUnary(ctx, req)
}

func (c *platformServiceClient) LinkGitHubRepository(ctx context.Context, req *connect.Request[platformv1.LinkGitHubRepositoryRequest]) (*connect.Response[platformv1.InspectSourceResponse], error) {
	return c.linkGitHubRepository.CallUnary(ctx, req)
}

func (c *platformServiceClient) InspectSource(ctx context.Context, req *connect.Request[platformv1.InspectSourceRequest]) (*connect.Response[platformv1.InspectSourceResponse], error) {
	return c.inspectSource.CallUnary(ctx, req)
}

func (c *platformServiceClient) CreateService(ctx context.Context, req *connect.Request[platformv1.CreateServiceRequest]) (*connect.Response[platformv1.Service], error) {
	return c.createService.CallUnary(ctx, req)
}

func (c *platformServiceClient) UpdateService(ctx context.Context, req *connect.Request[platformv1.UpdateServiceRequest]) (*connect.Response[platformv1.Service], error) {
	return c.updateService.CallUnary(ctx, req)
}

func (c *platformServiceClient) ScaleService(ctx context.Context, req *connect.Request[platformv1.ScaleServiceRequest]) (*connect.Response[platformv1.ServiceStatus], error) {
	return c.scaleService.CallUnary(ctx, req)
}

func (c *platformServiceClient) ApplyDeploymentAction(ctx context.Context, req *connect.Request[platformv1.ApplyDeploymentActionRequest]) (*connect.Response[platformv1.ServiceStatus], error) {
	return c.applyDeploymentAction.CallUnary(ctx, req)
}

func (c *platformServiceClient) DiscardServiceChanges(ctx context.Context, req *connect.Request[platformv1.DiscardServiceChangesRequest]) (*connect.Response[platformv1.Service], error) {
	return c.discardServiceChanges.CallUnary(ctx, req)
}

func (c *platformServiceClient) DeleteService(ctx context.Context, req *connect.Request[platformv1.DeleteServiceRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteService.CallUnary(ctx, req)
}

func (c *platformServiceClient) GetService(ctx context.Context, req *connect.Request[platformv1.GetServiceRequest]) (*connect.Response[platformv1.Service], error) {
	return c.getService.CallUnary(ctx, req)
}

func (c *platformServiceClient) ListServices(ctx context.Context, req *connect.Request[platformv1.ListServicesRequest]) (*connect.Response[platformv1.ListServicesResponse], error) {
	return c.listServices.CallUnary(ctx, req)
}

func (c *platformServiceClient) CreateVolume(ctx context.Context, req *connect.Request[platformv1.CreateVolumeRequest]) (*connect.Response[platformv1.Volume], error) {
	return c.createVolume.CallUnary(ctx, req)
}

func (c *platformServiceClient) DeleteVolume(ctx context.Context, req *connect.Request[platformv1.DeleteVolumeRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteVolume.CallUnary(ctx, req)
}

func (c *platformServiceClient) ListVolumes(ctx context.Context, req *connect.Request[platformv1.ListVolumesRequest]) (*connect.Response[platformv1.ListVolumesResponse], error) {
	return c.listVolumes.CallUnary(ctx, req)
}

func (c *platformServiceClient) CreateDomainBinding(ctx context.Context, req *connect.Request[platformv1.CreateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error) {
	return c.createDomainBinding.CallUnary(ctx, req)
}

func (c *platformServiceClient) GenerateDomainBinding(ctx context.Context, req *connect.Request[platformv1.GenerateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error) {
	return c.generateDomainBinding.CallUnary(ctx, req)
}

func (c *platformServiceClient) GetDomainBinding(ctx context.Context, req *connect.Request[platformv1.GetDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error) {
	return c.getDomainBinding.CallUnary(ctx, req)
}

func (c *platformServiceClient) ListDomainBindings(ctx context.Context, req *connect.Request[platformv1.ListDomainBindingsRequest]) (*connect.Response[platformv1.ListDomainBindingsResponse], error) {
	return c.listDomainBindings.CallUnary(ctx, req)
}

func (c *platformServiceClient) UpdateDomainBinding(ctx context.Context, req *connect.Request[platformv1.UpdateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error) {
	return c.updateDomainBinding.CallUnary(ctx, req)
}

func (c *platformServiceClient) DeleteDomainBinding(ctx context.Context, req *connect.Request[platformv1.DeleteDomainBindingRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteDomainBinding.CallUnary(ctx, req)
}

func (c *platformServiceClient) GetServiceStatus(ctx context.Context, req *connect.Request[platformv1.GetServiceStatusRequest]) (*connect.Response[platformv1.ServiceStatus], error) {
	return c.getServiceStatus.CallUnary(ctx, req)
}

func (c *platformServiceClient) ListServiceLogs(ctx context.Context, req *connect.Request[platformv1.ListServiceLogsRequest]) (*connect.Response[platformv1.ListServiceLogsResponse], error) {
	return c.listServiceLogs.CallUnary(ctx, req)
}

func (c *platformServiceClient) ListServiceDeployments(ctx context.Context, req *connect.Request[platformv1.ListServiceDeploymentsRequest]) (*connect.Response[platformv1.ListServiceDeploymentsResponse], error) {
	return c.listServiceDeployments.CallUnary(ctx, req)
}

func (c *platformServiceClient) ListAgents(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

type PlatformServiceHandler interface {
	CreateProject(context.Context, *connect.Request[platformv1.CreateProjectRequest]) (*connect.Response[platformv1.Project], error)
	ListProjects(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.ListProjectsResponse], error)
	GetProject(context.Context, *connect.Request[platformv1.GetProjectRequest]) (*connect.Response[platformv1.Project], error)
	ListEnvironments(context.Context, *connect.Request[platformv1.ListEnvironmentsRequest]) (*connect.Response[platformv1.ListEnvironmentsResponse], error)
	GetEnvironment(context.Context, *connect.Request[platformv1.GetEnvironmentRequest]) (*connect.Response[platformv1.Environment], error)
	CreateEnvironment(context.Context, *connect.Request[platformv1.CreateEnvironmentRequest]) (*connect.Response[platformv1.Environment], error)
	DuplicateEnvironment(context.Context, *connect.Request[platformv1.DuplicateEnvironmentRequest]) (*connect.Response[platformv1.Environment], error)
	RenameEnvironment(context.Context, *connect.Request[platformv1.RenameEnvironmentRequest]) (*connect.Response[platformv1.Environment], error)
	DeleteEnvironment(context.Context, *connect.Request[platformv1.DeleteEnvironmentRequest]) (*connect.Response[emptypb.Empty], error)
	ReleaseEnvironment(context.Context, *connect.Request[platformv1.ReleaseEnvironmentRequest]) (*connect.Response[platformv1.ReleaseEnvironmentResponse], error)
	LinkGitHubRepository(context.Context, *connect.Request[platformv1.LinkGitHubRepositoryRequest]) (*connect.Response[platformv1.InspectSourceResponse], error)
	InspectSource(context.Context, *connect.Request[platformv1.InspectSourceRequest]) (*connect.Response[platformv1.InspectSourceResponse], error)
	CreateService(context.Context, *connect.Request[platformv1.CreateServiceRequest]) (*connect.Response[platformv1.Service], error)
	UpdateService(context.Context, *connect.Request[platformv1.UpdateServiceRequest]) (*connect.Response[platformv1.Service], error)
	ScaleService(context.Context, *connect.Request[platformv1.ScaleServiceRequest]) (*connect.Response[platformv1.ServiceStatus], error)
	ApplyDeploymentAction(context.Context, *connect.Request[platformv1.ApplyDeploymentActionRequest]) (*connect.Response[platformv1.ServiceStatus], error)
	DiscardServiceChanges(context.Context, *connect.Request[platformv1.DiscardServiceChangesRequest]) (*connect.Response[platformv1.Service], error)
	DeleteService(context.Context, *connect.Request[platformv1.DeleteServiceRequest]) (*connect.Response[emptypb.Empty], error)
	GetService(context.Context, *connect.Request[platformv1.GetServiceRequest]) (*connect.Response[platformv1.Service], error)
	ListServices(context.Context, *connect.Request[platformv1.ListServicesRequest]) (*connect.Response[platformv1.ListServicesResponse], error)
	CreateVolume(context.Context, *connect.Request[platformv1.CreateVolumeRequest]) (*connect.Response[platformv1.Volume], error)
	DeleteVolume(context.Context, *connect.Request[platformv1.DeleteVolumeRequest]) (*connect.Response[emptypb.Empty], error)
	ListVolumes(context.Context, *connect.Request[platformv1.ListVolumesRequest]) (*connect.Response[platformv1.ListVolumesResponse], error)
	CreateDomainBinding(context.Context, *connect.Request[platformv1.CreateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error)
	GenerateDomainBinding(context.Context, *connect.Request[platformv1.GenerateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error)
	GetDomainBinding(context.Context, *connect.Request[platformv1.GetDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error)
	ListDomainBindings(context.Context, *connect.Request[platformv1.ListDomainBindingsRequest]) (*connect.Response[platformv1.ListDomainBindingsResponse], error)
	UpdateDomainBinding(context.Context, *connect.Request[platformv1.UpdateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error)
	DeleteDomainBinding(context.Context, *connect.Request[platformv1.DeleteDomainBindingRequest]) (*connect.Response[emptypb.Empty], error)
	GetServiceStatus(context.Context, *connect.Request[platformv1.GetServiceStatusRequest]) (*connect.Response[platformv1.ServiceStatus], error)
	ListServiceLogs(context.Context, *connect.Request[platformv1.ListServiceLogsRequest]) (*connect.Response[platformv1.ListServiceLogsResponse], error)
	ListServiceDeployments(context.Context, *connect.Request[platformv1.ListServiceDeploymentsRequest]) (*connect.Response[platformv1.ListServiceDeploymentsResponse], error)
	ListAgents(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.ListAgentsResponse], error)
}

func NewPlatformServiceHandler(svc PlatformServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	platformServiceMethods := platformv1.File_platform_proto.Services().ByName("PlatformService").Methods()
	platformServiceCreateProjectHandler := connect.NewUnaryHandler(
		PlatformServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(platformServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceListProjectsHandler := connect.NewUnaryHandler(
		PlatformServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(platformServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceGetProjectHandler := connect.NewUnaryHandler(
		PlatformServiceGetProjectProcedure,
		svc.GetProject,
		connect.WithSchema(platformServiceMethods.ByName("GetProject")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceListEnvironmentsHandler := connect.NewUnaryHandler(
		PlatformServiceListEnvironmentsProcedure,
		svc.ListEnvironments,
		connect.WithSchema(platformServiceMethods.ByName("ListEnvironments")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceGetEnvironmentHandler := connect.NewUnaryHandler(
		PlatformServiceGetEnvironmentProcedure,
		svc.GetEnvironment,
		connect.WithSchema(platformServiceMethods.ByName("GetEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceCreateEnvironmentHandler := connect.NewUnaryHandler(
		PlatformServiceCreateEnvironmentProcedure,
		svc.CreateEnvironment,
		connect.WithSchema(platformServiceMethods.ByName("CreateEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceDuplicateEnvironmentHandler := connect.NewUnaryHandler(
		PlatformServiceDuplicateEnvironmentProcedure,
		svc.DuplicateEnvironment,
		connect.WithSchema(platformServiceMethods.ByName("DuplicateEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceRenameEnvironmentHandler := connect.NewUnaryHandler(
		PlatformServiceRenameEnvironmentProcedure,
		svc.RenameEnvironment,
		connect.WithSchema(platformServiceMethods.ByName("RenameEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceDeleteEnvironmentHandler := connect.NewUnaryHandler(
		PlatformServiceDeleteEnvironmentProcedure,
		svc.DeleteEnvironment,
		connect.WithSchema(platformServiceMethods.ByName("DeleteEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceReleaseEnvironmentHandler := connect.NewUnaryHandler(
		PlatformServiceReleaseEnvironmentProcedure,
		svc.ReleaseEnvironment,
		connect.WithSchema(platformServiceMethods.ByName("ReleaseEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceLinkGitHubRepositoryHandler := connect.NewUnaryHandler(
		PlatformServiceLinkGitHubRepositoryProcedure,
		svc.LinkGitHubRepository,
		connect.WithSchema(platformServiceMethods.ByName("LinkGitHubRepository")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceInspectSourceHandler := connect.NewUnaryHandler(
		PlatformServiceInspectSourceProcedure,
		svc.InspectSource,
		connect.WithSchema(platformServiceMethods.ByName("InspectSource")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceCreateServiceHandler := connect.NewUnaryHandler(
		PlatformServiceCreateServiceProcedure,
		svc.CreateService,
		connect.WithSchema(platformServiceMethods.ByName("CreateService")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceUpdateServiceHandler := connect.NewUnaryHandler(
		PlatformServiceUpdateServiceProcedure,
		svc.UpdateService,
		connect.WithSchema(platformServiceMethods.ByName("UpdateService")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceScaleServiceHandler := connect.NewUnaryHandler(
		PlatformServiceScaleServiceProcedure,
		svc.ScaleService,
		connect.WithSchema(platformServiceMethods.ByName("ScaleService")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceApplyDeploymentActionHandler := connect.NewUnaryHandler(
		PlatformServiceApplyDeploymentActionProcedure,
		svc.ApplyDeploymentAction,
		connect.WithSchema(platformServiceMethods.ByName("ApplyDeploymentAction")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceDiscardServiceChangesHandler := connect.NewUnaryHandler(
		PlatformServiceDiscardServiceChangesProcedure,
		svc.DiscardServiceChanges,
		connect.WithSchema(platformServiceMethods.ByName("DiscardServiceChanges")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceDeleteServiceHandler := connect.NewUnaryHandler(
		PlatformServiceDeleteServiceProcedure,
		svc.DeleteService,
		connect.WithSchema(platformServiceMethods.ByName("DeleteService")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceGetServiceHandler := connect.NewUnaryHandler(
		PlatformServiceGetServiceProcedure,
		svc.GetService,
		connect.WithSchema(platformServiceMethods.ByName("GetService")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceListServicesHandler := connect.NewUnaryHandler(
		PlatformServiceListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(platformServiceMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceCreateVolumeHandler := connect.NewUnaryHandler(
		PlatformServiceCreateVolumeProcedure,
		svc.CreateVolume,
		connect.WithSchema(platformServiceMethods.ByName("CreateVolume")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceDeleteVolumeHandler := connect.NewUnaryHandler(
		PlatformServiceDeleteVolumeProcedure,
		svc.DeleteVolume,
		connect.WithSchema(platformServiceMethods.ByName("DeleteVolume")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceListVolumesHandler := connect.NewUnaryHandler(
		PlatformServiceListVolumesProcedure,
		svc.ListVolumes,
		connect.WithSchema(platformServiceMethods.ByName("ListVolumes")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceCreateDomainBindingHandler := connect.NewUnaryHandler(
		PlatformServiceCreateDomainBindingProcedure,
		svc.CreateDomainBinding,
		connect.WithSchema(platformServiceMethods.ByName("CreateDomainBinding")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceGenerateDomainBindingHandler := connect.NewUnaryHandler(
		PlatformServiceGenerateDomainBindingProcedure,
		svc.GenerateDomainBinding,
		connect.WithSchema(platformServiceMethods.ByName("GenerateDomainBinding")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceGetDomainBindingHandler := connect.NewUnaryHandler(
		PlatformServiceGetDomainBindingProcedure,
		svc.GetDomainBinding,
		connect.WithSchema(platformServiceMethods.ByName("GetDomainBinding")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceListDomainBindingsHandler := connect.NewUnaryHandler(
		PlatformServiceListDomainBindingsProcedure,
		svc.ListDomainBindings,
		connect.WithSchema(platformServiceMethods.ByName("ListDomainBindings")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceUpdateDomainBindingHandler := connect.NewUnaryHandler(
		PlatformServiceUpdateDomainBindingProcedure,
		svc.UpdateDomainBinding,
		connect.WithSchema(platformServiceMethods.ByName("UpdateDomainBinding")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceDeleteDomainBindingHandler := connect.NewUnaryHandler(
		PlatformServiceDeleteDomainBindingProcedure,
		svc.DeleteDomainBinding,
		connect.WithSchema(platformServiceMethods.ByName("DeleteDomainBinding")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceGetServiceStatusHandler := connect.NewUnaryHandler(
		PlatformServiceGetServiceStatusProcedure,
		svc.GetServiceStatus,
		connect.WithSchema(platformServiceMethods.ByName("GetServiceStatus")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceListServiceLogsHandler := connect.NewUnaryHandler(
		PlatformServiceListServiceLogsProcedure,
		svc.ListServiceLogs,
		connect.WithSchema(platformServiceMethods.ByName("ListServiceLogs")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceListServiceDeploymentsHandler := connect.NewUnaryHandler(
		PlatformServiceListServiceDeploymentsProcedure,
		svc.ListServiceDeployments,
		connect.WithSchema(platformServiceMethods.ByName("ListServiceDeployments")),
		connect.WithHandlerOptions(opts...),
	)
	platformServiceListAgentsHandler := connect.NewUnaryHandler(
		PlatformServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(platformServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.v1.PlatformService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PlatformServiceCreateProjectProcedure:
			platformServiceCreateProjectHandler.ServeHTTP(w, r)
		case PlatformServiceListProjectsProcedure:
			platformServiceListProjectsHandler.ServeHTTP(w, r)
		case PlatformServiceGetProjectProcedure:
			platformServiceGetProjectHandler.ServeHTTP(w, r)
		case PlatformServiceListEnvironmentsProcedure:
			platformServiceListEnvironmentsHandler.ServeHTTP(w, r)
		case PlatformServiceGetEnvironmentProcedure:
			platformServiceGetEnvironmentHandler.ServeHTTP(w, r)
		case PlatformServiceCreateEnvironmentProcedure:
			platformServiceCreateEnvironmentHandler.ServeHTTP(w, r)
		case PlatformServiceDuplicateEnvironmentProcedure:
			platformServiceDuplicateEnvironmentHandler.ServeHTTP(w, r)
		case PlatformServiceRenameEnvironmentProcedure:
			platformServiceRenameEnvironmentHandler.ServeHTTP(w, r)
		case PlatformServiceDeleteEnvironmentProcedure:
			platformServiceDeleteEnvironmentHandler.ServeHTTP(w, r)
		case PlatformServiceReleaseEnvironmentProcedure:
			platformServiceReleaseEnvironmentHandler.ServeHTTP(w, r)
		case PlatformServiceLinkGitHubRepositoryProcedure:
			platformServiceLinkGitHubRepositoryHandler.ServeHTTP(w, r)
		case PlatformServiceInspectSourceProcedure:
			platformServiceInspectSourceHandler.ServeHTTP(w, r)
		case PlatformServiceCreateServiceProcedure:
			platformServiceCreateServiceHandler.ServeHTTP(w, r)
		case PlatformServiceUpdateServiceProcedure:
			platformServiceUpdateServiceHandler.ServeHTTP(w, r)
		case PlatformServiceScaleServiceProcedure:
			platformServiceScaleServiceHandler.ServeHTTP(w, r)
		case PlatformServiceApplyDeploymentActionProcedure:
			platformServiceApplyDeploymentActionHandler.ServeHTTP(w, r)
		case PlatformServiceDiscardServiceChangesProcedure:
			platformServiceDiscardServiceChangesHandler.ServeHTTP(w, r)
		case PlatformServiceDeleteServiceProcedure:
			platformServiceDeleteServiceHandler.ServeHTTP(w, r)
		case PlatformServiceGetServiceProcedure:
			platformServiceGetServiceHandler.ServeHTTP(w, r)
		case PlatformServiceListServicesProcedure:
			platformServiceListServicesHandler.ServeHTTP(w, r)
		case PlatformServiceCreateVolumeProcedure:
			platformServiceCreateVolumeHandler.ServeHTTP(w, r)
		case PlatformServiceDeleteVolumeProcedure:
			platformServiceDeleteVolumeHandler.ServeHTTP(w, r)
		case PlatformServiceListVolumesProcedure:
			platformServiceListVolumesHandler.ServeHTTP(w, r)
		case PlatformServiceCreateDomainBindingProcedure:
			platformServiceCreateDomainBindingHandler.ServeHTTP(w, r)
		case PlatformServiceGenerateDomainBindingProcedure:
			platformServiceGenerateDomainBindingHandler.ServeHTTP(w, r)
		case PlatformServiceGetDomainBindingProcedure:
			platformServiceGetDomainBindingHandler.ServeHTTP(w, r)
		case PlatformServiceListDomainBindingsProcedure:
			platformServiceListDomainBindingsHandler.ServeHTTP(w, r)
		case PlatformServiceUpdateDomainBindingProcedure:
			platformServiceUpdateDomainBindingHandler.ServeHTTP(w, r)
		case PlatformServiceDeleteDomainBindingProcedure:
			platformServiceDeleteDomainBindingHandler.ServeHTTP(w, r)
		case PlatformServiceGetServiceStatusProcedure:
			platformServiceGetServiceStatusHandler.ServeHTTP(w, r)
		case PlatformServiceListServiceLogsProcedure:
			platformServiceListServiceLogsHandler.ServeHTTP(w, r)
		case PlatformServiceListServiceDeploymentsProcedure:
			platformServiceListServiceDeploymentsHandler.ServeHTTP(w, r)
		case PlatformServiceListAgentsProcedure:
			platformServiceListAgentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

type UnimplementedPlatformServiceHandler struct{}

func (UnimplementedPlatformServiceHandler) CreateProject(context.Context, *connect.Request[platformv1.CreateProjectRequest]) (*connect.Response[platformv1.Project], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.CreateProject is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ListProjects(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ListProjects is not implemented"))
}

func (UnimplementedPlatformServiceHandler) GetProject(context.Context, *connect.Request[platformv1.GetProjectRequest]) (*connect.Response[platformv1.Project], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.GetProject is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ListEnvironments(context.Context, *connect.Request[platformv1.ListEnvironmentsRequest]) (*connect.Response[platformv1.ListEnvironmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ListEnvironments is not implemented"))
}

func (UnimplementedPlatformServiceHandler) GetEnvironment(context.Context, *connect.Request[platformv1.GetEnvironmentRequest]) (*connect.Response[platformv1.Environment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.GetEnvironment is not implemented"))
}

func (UnimplementedPlatformServiceHandler) CreateEnvironment(context.Context, *connect.Request[platformv1.CreateEnvironmentRequest]) (*connect.Response[platformv1.Environment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.CreateEnvironment is not implemented"))
}

func (UnimplementedPlatformServiceHandler) DuplicateEnvironment(context.Context, *connect.Request[platformv1.DuplicateEnvironmentRequest]) (*connect.Response[platformv1.Environment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.DuplicateEnvironment is not implemented"))
}

func (UnimplementedPlatformServiceHandler) RenameEnvironment(context.Context, *connect.Request[platformv1.RenameEnvironmentRequest]) (*connect.Response[platformv1.Environment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.RenameEnvironment is not implemented"))
}

func (UnimplementedPlatformServiceHandler) DeleteEnvironment(context.Context, *connect.Request[platformv1.DeleteEnvironmentRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.DeleteEnvironment is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ReleaseEnvironment(context.Context, *connect.Request[platformv1.ReleaseEnvironmentRequest]) (*connect.Response[platformv1.ReleaseEnvironmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ReleaseEnvironment is not implemented"))
}

func (UnimplementedPlatformServiceHandler) LinkGitHubRepository(context.Context, *connect.Request[platformv1.LinkGitHubRepositoryRequest]) (*connect.Response[platformv1.InspectSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.LinkGitHubRepository is not implemented"))
}

func (UnimplementedPlatformServiceHandler) InspectSource(context.Context, *connect.Request[platformv1.InspectSourceRequest]) (*connect.Response[platformv1.InspectSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.InspectSource is not implemented"))
}

func (UnimplementedPlatformServiceHandler) CreateService(context.Context, *connect.Request[platformv1.CreateServiceRequest]) (*connect.Response[platformv1.Service], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.CreateService is not implemented"))
}

func (UnimplementedPlatformServiceHandler) UpdateService(context.Context, *connect.Request[platformv1.UpdateServiceRequest]) (*connect.Response[platformv1.Service], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.UpdateService is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ScaleService(context.Context, *connect.Request[platformv1.ScaleServiceRequest]) (*connect.Response[platformv1.ServiceStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ScaleService is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ApplyDeploymentAction(context.Context, *connect.Request[platformv1.ApplyDeploymentActionRequest]) (*connect.Response[platformv1.ServiceStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ApplyDeploymentAction is not implemented"))
}

func (UnimplementedPlatformServiceHandler) DiscardServiceChanges(context.Context, *connect.Request[platformv1.DiscardServiceChangesRequest]) (*connect.Response[platformv1.Service], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.DiscardServiceChanges is not implemented"))
}

func (UnimplementedPlatformServiceHandler) DeleteService(context.Context, *connect.Request[platformv1.DeleteServiceRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.DeleteService is not implemented"))
}

func (UnimplementedPlatformServiceHandler) GetService(context.Context, *connect.Request[platformv1.GetServiceRequest]) (*connect.Response[platformv1.Service], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.GetService is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ListServices(context.Context, *connect.Request[platformv1.ListServicesRequest]) (*connect.Response[platformv1.ListServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ListServices is not implemented"))
}

func (UnimplementedPlatformServiceHandler) CreateVolume(context.Context, *connect.Request[platformv1.CreateVolumeRequest]) (*connect.Response[platformv1.Volume], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.CreateVolume is not implemented"))
}

func (UnimplementedPlatformServiceHandler) DeleteVolume(context.Context, *connect.Request[platformv1.DeleteVolumeRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.DeleteVolume is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ListVolumes(context.Context, *connect.Request[platformv1.ListVolumesRequest]) (*connect.Response[platformv1.ListVolumesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ListVolumes is not implemented"))
}

func (UnimplementedPlatformServiceHandler) CreateDomainBinding(context.Context, *connect.Request[platformv1.CreateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.CreateDomainBinding is not implemented"))
}

func (UnimplementedPlatformServiceHandler) GenerateDomainBinding(context.Context, *connect.Request[platformv1.GenerateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.GenerateDomainBinding is not implemented"))
}

func (UnimplementedPlatformServiceHandler) GetDomainBinding(context.Context, *connect.Request[platformv1.GetDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.GetDomainBinding is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ListDomainBindings(context.Context, *connect.Request[platformv1.ListDomainBindingsRequest]) (*connect.Response[platformv1.ListDomainBindingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ListDomainBindings is not implemented"))
}

func (UnimplementedPlatformServiceHandler) UpdateDomainBinding(context.Context, *connect.Request[platformv1.UpdateDomainBindingRequest]) (*connect.Response[platformv1.DomainBinding], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.UpdateDomainBinding is not implemented"))
}

func (UnimplementedPlatformServiceHandler) DeleteDomainBinding(context.Context, *connect.Request[platformv1.DeleteDomainBindingRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.DeleteDomainBinding is not implemented"))
}

func (UnimplementedPlatformServiceHandler) GetServiceStatus(context.Context, *connect.Request[platformv1.GetServiceStatusRequest]) (*connect.Response[platformv1.ServiceStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.GetServiceStatus is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ListServiceLogs(context.Context, *connect.Request[platformv1.ListServiceLogsRequest]) (*connect.Response[platformv1.ListServiceLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ListServiceLogs is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ListServiceDeployments(context.Context, *connect.Request[platformv1.ListServiceDeploymentsRequest]) (*connect.Response[platformv1.ListServiceDeploymentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ListServiceDeployments is not implemented"))
}

func (UnimplementedPlatformServiceHandler) ListAgents(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.PlatformService.ListAgents is not implemented"))
}

type BuilderServiceClient interface {
	ClaimBuild(context.Context, *connect.Request[platformv1.ClaimBuildRequest]) (*connect.Response[platformv1.BuildJob], error)
	DownloadSourceSnapshot(context.Context, *connect.Request[platformv1.DownloadSourceSnapshotRequest]) (*connect.ServerStreamForClient[platformv1.SourceSnapshotChunk], error)
	ReportBuildHeartbeat(context.Context, *connect.Request[platformv1.BuilderHeartbeatRequest]) (*connect.Response[emptypb.Empty], error)
	ReportBuildLogs(context.Context, *connect.Request[platformv1.ReportBuildLogsRequest]) (*connect.Response[emptypb.Empty], error)
	CompleteBuild(context.Context, *connect.Request[platformv1.CompleteBuildRequest]) (*connect.Response[emptypb.Empty], error)
}

func NewBuilderServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BuilderServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	builderServiceMethods := platformv1.File_platform_proto.Services().ByName("BuilderService").Methods()
	return &builderServiceClient{
		claimBuild: connect.NewClient[platformv1.ClaimBuildRequest, platformv1.BuildJob](
			httpClient,
			baseURL+BuilderServiceClaimBuildProcedure,
			connect.WithSchema(builderServiceMethods.ByName("ClaimBuild")),
			connect.WithClientOptions(opts...),
		),
		downloadSourceSnapshot: connect.NewClient[platformv1.DownloadSourceSnapshotRequest, platformv1.SourceSnapshotChunk](
			httpClient,
			baseURL+BuilderServiceDownloadSourceSnapshotProcedure,
			connect.WithSchema(builderServiceMethods.ByName("DownloadSourceSnapshot")),
			connect.WithClientOptions(opts...),
		),
		reportBuildHeartbeat: connect.NewClient[platformv1.BuilderHeartbeatRequest, emptypb.Empty](
			httpClient,
			baseURL+BuilderServiceReportBuildHeartbeatProcedure,
			connect.WithSchema(builderServiceMethods.ByName("ReportBuildHeartbeat")),
			connect.WithClientOptions(opts...),
		),
		reportBuildLogs: connect.NewClient[platformv1.ReportBuildLogsRequest, emptypb.Empty](
			httpClient,
			baseURL+BuilderServiceReportBuildLogsProcedure,
			connect.WithSchema(builderServiceMethods.ByName("ReportBuildLogs")),
			connect.WithClientOptions(opts...),
		),
		completeBuild: connect.NewClient[platformv1.CompleteBuildRequest, emptypb.Empty](
			httpClient,
			baseURL+BuilderServiceCompleteBuildProcedure,
			connect.WithSchema(builderServiceMethods.ByName("CompleteBuild")),
			connect.WithClientOptions(opts...),
		),
	}
}

type builderServiceClient struct {
	claimBuild             *connect.Client[platformv1.ClaimBuildRequest, platformv1.BuildJob]
	downloadSourceSnapshot *connect.Client[platformv1.DownloadSourceSnapshotRequest, platformv1.SourceSnapshotChunk]
	reportBuildHeartbeat   *connect.Client[platformv1.BuilderHeartbeatRequest, emptypb.Empty]
	reportBuildLogs        *connect.Client[platformv1.ReportBuildLogsRequest, emptypb.Empty]
	completeBuild          *connect.Client[platformv1.CompleteBuildRequest, emptypb.Empty]
}

func (c *builderServiceClient) ClaimBuild(ctx context.Context, req *connect.Request[platformv1.ClaimBuildRequest]) (*connect.Response[platformv1.BuildJob], error) {
	return c.claimBuild.CallUnary(ctx, req)
}

func (c *builderServiceClient) DownloadSourceSnapshot(ctx context.Context, req *connect.Request[platformv1.DownloadSourceSnapshotRequest]) (*connect.ServerStreamForClient[platformv1.SourceSnapshotChunk], error) {
	return c.downloadSourceSnapshot.CallServerStream(ctx, req)
}

func (c *builderServiceClient) ReportBuildHeartbeat(ctx context.Context, req *connect.Request[platformv1.BuilderHeartbeatRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.reportBuildHeartbeat.CallUnary(ctx, req)
}

func (c *builderServiceClient) ReportBuildLogs(ctx context.Context, req *connect.Request[platformv1.ReportBuildLogsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.reportBuildLogs.CallUnary(ctx, req)
}

func (c *builderServiceClient) CompleteBuild(ctx context.Context, req *connect.Request[platformv1.CompleteBuildRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.completeBuild.CallUnary(ctx, req)
}

type BuilderServiceHandler interface {
	ClaimBuild(context.Context, *connect.Request[platformv1.ClaimBuildRequest]) (*connect.Response[platformv1.BuildJob], error)
	DownloadSourceSnapshot(context.Context, *connect.Request[platformv1.DownloadSourceSnapshotRequest], *connect.ServerStream[platformv1.SourceSnapshotChunk]) error
	ReportBuildHeartbeat(context.Context, *connect.Request[platformv1.BuilderHeartbeatRequest]) (*connect.Response[emptypb.Empty], error)
	ReportBuildLogs(context.Context, *connect.Request[platformv1.ReportBuildLogsRequest]) (*connect.Response[emptypb.Empty], error)
	CompleteBuild(context.Context, *connect.Request[platformv1.CompleteBuildRequest]) (*connect.Response[emptypb.Empty], error)
}

func NewBuilderServiceHandler(svc BuilderServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	builderServiceMethods := platformv1.File_platform_proto.Services().ByName("BuilderService").Methods()
	builderServiceClaimBuildHandler := connect.NewUnaryHandler(
		BuilderServiceClaimBuildProcedure,
		svc.ClaimBuild,
		connect.WithSchema(builderServiceMethods.ByName("ClaimBuild")),
		connect.WithHandlerOptions(opts...),
	)
	builderServiceDownloadSourceSnapshotHandler := connect.NewServerStreamHandler(
		BuilderServiceDownloadSourceSnapshotProcedure,
		svc.DownloadSourceSnapshot,
		connect.WithSchema(builderServiceMethods.ByName("DownloadSourceSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	builderServiceReportBuildHeartbeatHandler := connect.NewUnaryHandler(
		BuilderServiceReportBuildHeartbeatProcedure,
		svc.ReportBuildHeartbeat,
		connect.WithSchema(builderServiceMethods.ByName("ReportBuildHeartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	builderServiceReportBuildLogsHandler := connect.NewUnaryHandler(
		BuilderServiceReportBuildLogsProcedure,
		svc.ReportBuildLogs,
		connect.WithSchema(builderServiceMethods.ByName("ReportBuildLogs")),
		connect.WithHandlerOptions(opts...),
	)
	builderServiceCompleteBuildHandler := connect.NewUnaryHandler(
		BuilderServiceCompleteBuildProcedure,
		svc.CompleteBuild,
		connect.WithSchema(builderServiceMethods.ByName("CompleteBuild")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.v1.BuilderService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BuilderServiceClaimBuildProcedure:
			builderServiceClaimBuildHandler.ServeHTTP(w, r)
		case BuilderServiceDownloadSourceSnapshotProcedure:
			builderServiceDownloadSourceSnapshotHandler.ServeHTTP(w, r)
		case BuilderServiceReportBuildHeartbeatProcedure:
			builderServiceReportBuildHeartbeatHandler.ServeHTTP(w, r)
		case BuilderServiceReportBuildLogsProcedure:
			builderServiceReportBuildLogsHandler.ServeHTTP(w, r)
		case BuilderServiceCompleteBuildProcedure:
			builderServiceCompleteBuildHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

type UnimplementedBuilderServiceHandler struct{}

func (UnimplementedBuilderServiceHandler) ClaimBuild(context.Context, *connect.Request[platformv1.ClaimBuildRequest]) (*connect.Response[platformv1.BuildJob], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.BuilderService.ClaimBuild is not implemented"))
}

func (UnimplementedBuilderServiceHandler) DownloadSourceSnapshot(context.Context, *connect.Request[platformv1.DownloadSourceSnapshotRequest], *connect.ServerStream[platformv1.SourceSnapshotChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.BuilderService.DownloadSourceSnapshot is not implemented"))
}

func (UnimplementedBuilderServiceHandler) ReportBuildHeartbeat(context.Context, *connect.Request[platformv1.BuilderHeartbeatRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.BuilderService.ReportBuildHeartbeat is not implemented"))
}

func (UnimplementedBuilderServiceHandler) ReportBuildLogs(context.Context, *connect.Request[platformv1.ReportBuildLogsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.BuilderService.ReportBuildLogs is not implemented"))
}

func (UnimplementedBuilderServiceHandler) CompleteBuild(context.Context, *connect.Request[platformv1.CompleteBuildRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.BuilderService.CompleteBuild is not implemented"))
}

type OpsServiceClient interface {
	IngestGitHubWebhook(context.Context, *connect.Request[platformv1.IngestGitHubWebhookRequest]) (*connect.Response[emptypb.Empty], error)
	ListFleet(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.Fleet], error)
	CreateAgent(context.Context, *connect.Request[platformv1.CreateAgentRequest]) (*connect.Response[platformv1.AgentEnrollment], error)
	UpdateAgent(context.Context, *connect.Request[platformv1.UpdateAgentRequest]) (*connect.Response[platformv1.Agent], error)
	SetAgentLifecycle(context.Context, *connect.Request[platformv1.SetAgentLifecycleRequest]) (*connect.Response[platformv1.Agent], error)
}

func NewOpsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OpsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	opsServiceMethods := platformv1.File_platform_proto.Services().ByName("OpsService").Methods()
	return &opsServiceClient{
		ingestGitHubWebhook: connect.NewClient[platformv1.IngestGitHubWebhookRequest, emptypb.Empty](
			httpClient,
			baseURL+OpsServiceIngestGitHubWebhookProcedure,
			connect.WithSchema(opsServiceMethods.ByName("IngestGitHubWebhook")),
			connect.WithClientOptions(opts...),
		),
		listFleet: connect.NewClient[emptypb.Empty, platformv1.Fleet](
			httpClient,
			baseURL+OpsServiceListFleetProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ListFleet")),
			connect.WithClientOptions(opts...),
		),
		createAgent: connect.NewClient[platformv1.CreateAgentRequest, platformv1.AgentEnrollment](
			httpClient,
			baseURL+OpsServiceCreateAgentProcedure,
			connect.WithSchema(opsServiceMethods.ByName("CreateAgent")),
			connect.WithClientOptions(opts...),
		),
		updateAgent: connect.NewClient[platformv1.UpdateAgentRequest, platformv1.Agent](
			httpClient,
			baseURL+OpsServiceUpdateAgentProcedure,
			connect.WithSchema(opsServiceMethods.ByName("UpdateAgent")),
			connect.WithClientOptions(opts...),
		),
		setAgentLifecycle: connect.NewClient[platformv1.SetAgentLifecycleRequest, platformv1.Agent](
			httpClient,
			baseURL+OpsServiceSetAgentLifecycleProcedure,
			connect.WithSchema(opsServiceMethods.ByName("SetAgentLifecycle")),
			connect.WithClientOptions(opts...),
		),
	}
}

type opsServiceClient struct {
	ingestGitHubWebhook *connect.Client[platformv1.IngestGitHubWebhookRequest, emptypb.Empty]
	listFleet           *connect.Client[emptypb.Empty, platformv1.Fleet]
	createAgent         *connect.Client[platformv1.CreateAgentRequest, platformv1.AgentEnrollment]
	updateAgent         *connect.Client[platformv1.UpdateAgentRequest, platformv1.Agent]
	setAgentLifecycle   *connect.Client[platformv1.SetAgentLifecycleRequest, platformv1.Agent]
}

func (c *opsServiceClient) IngestGitHubWebhook(ctx context.Context, req *connect.Request[platformv1.IngestGitHubWebhookRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.ingestGitHubWebhook.CallUnary(ctx, req)
}

func (c *opsServiceClient) ListFleet(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.Fleet], error) {
	return c.listFleet.CallUnary(ctx, req)
}

func (c *opsServiceClient) CreateAgent(ctx context.Context, req *connect.Request[platformv1.CreateAgentRequest]) (*connect.Response[platformv1.AgentEnrollment], error) {
	return c.createAgent.CallUnary(ctx, req)
}

func (c *opsServiceClient) UpdateAgent(ctx context.Context, req *connect.Request[platformv1.UpdateAgentRequest]) (*connect.Response[platformv1.Agent], error) {
	return c.updateAgent.CallUnary(ctx, req)
}

func (c *opsServiceClient) SetAgentLifecycle(ctx context.Context, req *connect.Request[platformv1.SetAgentLifecycleRequest]) (*connect.Response[platformv1.Agent], error) {
	return c.setAgentLifecycle.CallUnary(ctx, req)
}

type OpsServiceHandler interface {
	IngestGitHubWebhook(context.Context, *connect.Request[platformv1.IngestGitHubWebhookRequest]) (*connect.Response[emptypb.Empty], error)
	ListFleet(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.Fleet], error)
	CreateAgent(context.Context, *connect.Request[platformv1.CreateAgentRequest]) (*connect.Response[platformv1.AgentEnrollment], error)
	UpdateAgent(context.Context, *connect.Request[platformv1.UpdateAgentRequest]) (*connect.Response[platformv1.Agent], error)
	SetAgentLifecycle(context.Context, *connect.Request[platformv1.SetAgentLifecycleRequest]) (*connect.Response[platformv1.Agent], error)
}

func NewOpsServiceHandler(svc OpsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	opsServiceMethods := platformv1.File_platform_proto.Services().ByName("OpsService").Methods()
	opsServiceIngestGitHubWebhookHandler := connect.NewUnaryHandler(
		OpsServiceIngestGitHubWebhookProcedure,
		svc.IngestGitHubWebhook,
		connect.WithSchema(opsServiceMethods.ByName("IngestGitHubWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceListFleetHandler := connect.NewUnaryHandler(
		OpsServiceListFleetProcedure,
		svc.ListFleet,
		connect.WithSchema(opsServiceMethods.ByName("ListFleet")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceCreateAgentHandler := connect.NewUnaryHandler(
		OpsServiceCreateAgentProcedure,
		svc.CreateAgent,
		connect.WithSchema(opsServiceMethods.ByName("CreateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceUpdateAgentHandler := connect.NewUnaryHandler(
		OpsServiceUpdateAgentProcedure,
		svc.UpdateAgent,
		connect.WithSchema(opsServiceMethods.ByName("UpdateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceSetAgentLifecycleHandler := connect.NewUnaryHandler(
		OpsServiceSetAgentLifecycleProcedure,
		svc.SetAgentLifecycle,
		connect.WithSchema(opsServiceMethods.ByName("SetAgentLifecycle")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.v1.OpsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OpsServiceIngestGitHubWebhookProcedure:
			opsServiceIngestGitHubWebhookHandler.ServeHTTP(w, r)
		case OpsServiceListFleetProcedure:
			opsServiceListFleetHandler.ServeHTTP(w, r)
		case OpsServiceCreateAgentProcedure:
			opsServiceCreateAgentHandler.ServeHTTP(w, r)
		case OpsServiceUpdateAgentProcedure:
			opsServiceUpdateAgentHandler.ServeHTTP(w, r)
		case OpsServiceSetAgentLifecycleProcedure:
			opsServiceSetAgentLifecycleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

type UnimplementedOpsServiceHandler struct{}

func (UnimplementedOpsServiceHandler) IngestGitHubWebhook(context.Context, *connect.Request[platformv1.IngestGitHubWebhookRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.OpsService.IngestGitHubWebhook is not implemented"))
}

func (UnimplementedOpsServiceHandler) ListFleet(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[platformv1.Fleet], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.OpsService.ListFleet is not implemented"))
}

func (UnimplementedOpsServiceHandler) CreateAgent(context.Context, *connect.Request[platformv1.CreateAgentRequest]) (*connect.Response[platformv1.AgentEnrollment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.OpsService.CreateAgent is not implemented"))
}

func (UnimplementedOpsServiceHandler) UpdateAgent(context.Context, *connect.Request[platformv1.UpdateAgentRequest]) (*connect.Response[platformv1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.OpsService.UpdateAgent is not implemented"))
}

func (UnimplementedOpsServiceHandler) SetAgentLifecycle(context.Context, *connect.Request[platformv1.SetAgentLifecycleRequest]) (*connect.Response[platformv1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.OpsService.SetAgentLifecycle is not implemented"))
}
