// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package firewall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type firewallConnectionKey struct {
	_        structs.HostLayout
	SrcIp    [16]uint8
	DstIp    [16]uint8
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad1     uint8
	Pad2     uint16
}

type firewallContainerPolicy struct {
	_         structs.HostLayout
	ProjectId uint32
	Ipv6      [16]uint8
}

type firewallHostIpValue struct {
	_  structs.HostLayout
	Ip [16]uint8
}

type firewallIdentityKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	IpAddress [16]uint8
}

type firewallIdentityValue struct {
	_           structs.HostLayout
	ProjectId   uint32
	HostIp      [16]uint8
	VethIfindex uint32
}

// loadFirewall returns the embedded CollectionSpec for firewall.
func loadFirewall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FirewallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load firewall: %w", err)
	}

	return spec, err
}

// loadFirewallObjects loads firewall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*firewallObjects
//	*firewallPrograms
//	*firewallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFirewallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFirewall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// firewallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallSpecs struct {
	firewallProgramSpecs
	firewallMapSpecs
	firewallVariableSpecs
}

// firewallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallProgramSpecs struct {
	TcxEgress  *ebpf.ProgramSpec `ebpf:"tcx_egress"`
	TcxIngress *ebpf.ProgramSpec `ebpf:"tcx_ingress"`
}

// firewallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallMapSpecs struct {
	ClusterIdentityTrie    *ebpf.MapSpec `ebpf:"cluster_identity_trie"`
	ConntrackInnerTemplate *ebpf.MapSpec `ebpf:"conntrack_inner_template"`
	ConntrackMatrix        *ebpf.MapSpec `ebpf:"conntrack_matrix"`
	ContainerPolicyMap     *ebpf.MapSpec `ebpf:"container_policy_map"`
	InterfaceRoleMap       *ebpf.MapSpec `ebpf:"interface_role_map"`
	LocalNodeMap           *ebpf.MapSpec `ebpf:"local_node_map"`
}

// firewallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallVariableSpecs struct {
}

// firewallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallObjects struct {
	firewallPrograms
	firewallMaps
	firewallVariables
}

func (o *firewallObjects) Close() error {
	return _FirewallClose(
		&o.firewallPrograms,
		&o.firewallMaps,
	)
}

// firewallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallMaps struct {
	ClusterIdentityTrie    *ebpf.Map `ebpf:"cluster_identity_trie"`
	ConntrackInnerTemplate *ebpf.Map `ebpf:"conntrack_inner_template"`
	ConntrackMatrix        *ebpf.Map `ebpf:"conntrack_matrix"`
	ContainerPolicyMap     *ebpf.Map `ebpf:"container_policy_map"`
	InterfaceRoleMap       *ebpf.Map `ebpf:"interface_role_map"`
	LocalNodeMap           *ebpf.Map `ebpf:"local_node_map"`
}

func (m *firewallMaps) Close() error {
	return _FirewallClose(
		m.ClusterIdentityTrie,
		m.ConntrackInnerTemplate,
		m.ConntrackMatrix,
		m.ContainerPolicyMap,
		m.InterfaceRoleMap,
		m.LocalNodeMap,
	)
}

// firewallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallVariables struct {
}

// firewallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallPrograms struct {
	TcxEgress  *ebpf.Program `ebpf:"tcx_egress"`
	TcxIngress *ebpf.Program `ebpf:"tcx_ingress"`
}

func (p *firewallPrograms) Close() error {
	return _FirewallClose(
		p.TcxEgress,
		p.TcxIngress,
	)
}

func _FirewallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed firewall_bpfeb.o
var _FirewallBytes []byte
