// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform.proto

package platformv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectKind int32

const (
	ProjectKind_PROJECT_KIND_UNSPECIFIED ProjectKind = 0
	ProjectKind_PROJECT_KIND_USER        ProjectKind = 1
	ProjectKind_PROJECT_KIND_MANAGED     ProjectKind = 2
)

// Enum value maps for ProjectKind.
var (
	ProjectKind_name = map[int32]string{
		0: "PROJECT_KIND_UNSPECIFIED",
		1: "PROJECT_KIND_USER",
		2: "PROJECT_KIND_MANAGED",
	}
	ProjectKind_value = map[string]int32{
		"PROJECT_KIND_UNSPECIFIED": 0,
		"PROJECT_KIND_USER":        1,
		"PROJECT_KIND_MANAGED":     2,
	}
)

func (x ProjectKind) Enum() *ProjectKind {
	p := new(ProjectKind)
	*p = x
	return p
}

func (x ProjectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_proto_enumTypes[0].Descriptor()
}

func (ProjectKind) Type() protoreflect.EnumType {
	return &file_platform_proto_enumTypes[0]
}

func (x ProjectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectKind.Descriptor instead.
func (ProjectKind) EnumDescriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{0}
}

type HealthCheck_Type int32

const (
	HealthCheck_TYPE_UNSPECIFIED HealthCheck_Type = 0
	HealthCheck_TYPE_HTTP        HealthCheck_Type = 1
	HealthCheck_TYPE_TCP         HealthCheck_Type = 2
)

// Enum value maps for HealthCheck_Type.
var (
	HealthCheck_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_HTTP",
		2: "TYPE_TCP",
	}
	HealthCheck_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_HTTP":        1,
		"TYPE_TCP":         2,
	}
)

func (x HealthCheck_Type) Enum() *HealthCheck_Type {
	p := new(HealthCheck_Type)
	*p = x
	return p
}

func (x HealthCheck_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheck_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_proto_enumTypes[1].Descriptor()
}

func (HealthCheck_Type) Type() protoreflect.EnumType {
	return &file_platform_proto_enumTypes[1]
}

func (x HealthCheck_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheck_Type.Descriptor instead.
func (HealthCheck_Type) EnumDescriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{2, 0}
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Kind          ProjectKind            `protobuf:"varint,4,opt,name=kind,proto3,enum=platform.v1.ProjectKind" json:"kind,omitempty"`
	SystemKey     string                 `protobuf:"bytes,5,opt,name=system_key,json=systemKey,proto3" json:"system_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetKind() ProjectKind {
	if x != nil {
		return x.Kind
	}
	return ProjectKind_PROJECT_KIND_UNSPECIFIED
}

func (x *Project) GetSystemKey() string {
	if x != nil {
		return x.SystemKey
	}
	return ""
}

type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{1}
}

func (x *Principal) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Principal) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Principal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type HealthCheck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            HealthCheck_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=platform.v1.HealthCheck_Type" json:"type,omitempty"`
	Path            string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Port            int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheck) GetType() HealthCheck_Type {
	if x != nil {
		return x.Type
	}
	return HealthCheck_TYPE_UNSPECIFIED
}

func (x *HealthCheck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HealthCheck) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HealthCheck) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheck) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ServiceSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Image           string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command         []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Args            []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env             map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CpuMillis       int64                  `protobuf:"varint,5,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	MemoryMebibytes int64                  `protobuf:"varint,6,opt,name=memory_mebibytes,json=memoryMebibytes,proto3" json:"memory_mebibytes,omitempty"`
	ContainerPort   int32                  `protobuf:"varint,7,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	HealthCheck     *HealthCheck           `protobuf:"bytes,8,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	VolumeName      string                 `protobuf:"bytes,9,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceSpec) Reset() {
	*x = ServiceSpec{}
	mi := &file_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSpec) ProtoMessage() {}

func (x *ServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSpec.ProtoReflect.Descriptor instead.
func (*ServiceSpec) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ServiceSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ServiceSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ServiceSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ServiceSpec) GetCpuMillis() int64 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *ServiceSpec) GetMemoryMebibytes() int64 {
	if x != nil {
		return x.MemoryMebibytes
	}
	return 0
}

func (x *ServiceSpec) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *ServiceSpec) GetHealthCheck() *HealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *ServiceSpec) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

type Service struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId         string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Spec              *ServiceSpec           `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	SpecRevision      int64                  `protobuf:"varint,5,opt,name=spec_revision,json=specRevision,proto3" json:"spec_revision,omitempty"`
	AllocatedAgentId  string                 `protobuf:"bytes,6,opt,name=allocated_agent_id,json=allocatedAgentId,proto3" json:"allocated_agent_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RolloutGeneration int64                  `protobuf:"varint,10,opt,name=rollout_generation,json=rolloutGeneration,proto3" json:"rollout_generation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{4}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Service) GetSpecRevision() int64 {
	if x != nil {
		return x.SpecRevision
	}
	return 0
}

func (x *Service) GetAllocatedAgentId() string {
	if x != nil {
		return x.AllocatedAgentId
	}
	return ""
}

func (x *Service) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Service) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Service) GetRolloutGeneration() int64 {
	if x != nil {
		return x.RolloutGeneration
	}
	return 0
}

type DomainBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainBinding) Reset() {
	*x = DomainBinding{}
	mi := &file_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainBinding) ProtoMessage() {}

func (x *DomainBinding) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainBinding.ProtoReflect.Descriptor instead.
func (*DomainBinding) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{5}
}

func (x *DomainBinding) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DomainBinding) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DomainBinding) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DomainBinding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DomainBinding) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	BoundAgentId  string                 `protobuf:"bytes,5,opt,name=bound_agent_id,json=boundAgentId,proto3" json:"bound_agent_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{6}
}

func (x *Volume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Volume) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Volume) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Volume) GetBoundAgentId() string {
	if x != nil {
		return x.BoundAgentId
	}
	return ""
}

func (x *Volume) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Agent struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AdvertiseAddr           string                 `protobuf:"bytes,3,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	Healthy                 bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	CpuMillisCapacity       int64                  `protobuf:"varint,5,opt,name=cpu_millis_capacity,json=cpuMillisCapacity,proto3" json:"cpu_millis_capacity,omitempty"`
	MemoryMebibytesCapacity int64                  `protobuf:"varint,6,opt,name=memory_mebibytes_capacity,json=memoryMebibytesCapacity,proto3" json:"memory_mebibytes_capacity,omitempty"`
	LastSeenAt              *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{7}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *Agent) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *Agent) GetCpuMillisCapacity() int64 {
	if x != nil {
		return x.CpuMillisCapacity
	}
	return 0
}

func (x *Agent) GetMemoryMebibytesCapacity() int64 {
	if x != nil {
		return x.MemoryMebibytesCapacity
	}
	return 0
}

func (x *Agent) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type AllocationStatus struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AllocationId             string                 `protobuf:"bytes,1,opt,name=allocation_id,json=allocationId,proto3" json:"allocation_id,omitempty"`
	ServiceId                string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AgentId                  string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DesiredSpecRevision      int64                  `protobuf:"varint,4,opt,name=desired_spec_revision,json=desiredSpecRevision,proto3" json:"desired_spec_revision,omitempty"`
	AppliedSpecRevision      int64                  `protobuf:"varint,5,opt,name=applied_spec_revision,json=appliedSpecRevision,proto3" json:"applied_spec_revision,omitempty"`
	Phase                    string                 `protobuf:"bytes,6,opt,name=phase,proto3" json:"phase,omitempty"`
	Message                  string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	EndpointAddr             string                 `protobuf:"bytes,8,opt,name=endpoint_addr,json=endpointAddr,proto3" json:"endpoint_addr,omitempty"`
	Healthy                  bool                   `protobuf:"varint,9,opt,name=healthy,proto3" json:"healthy,omitempty"`
	UpdatedAt                *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DesiredRolloutGeneration int64                  `protobuf:"varint,11,opt,name=desired_rollout_generation,json=desiredRolloutGeneration,proto3" json:"desired_rollout_generation,omitempty"`
	AppliedRolloutGeneration int64                  `protobuf:"varint,12,opt,name=applied_rollout_generation,json=appliedRolloutGeneration,proto3" json:"applied_rollout_generation,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AllocationStatus) Reset() {
	*x = AllocationStatus{}
	mi := &file_platform_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationStatus) ProtoMessage() {}

func (x *AllocationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationStatus.ProtoReflect.Descriptor instead.
func (*AllocationStatus) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{8}
}

func (x *AllocationStatus) GetAllocationId() string {
	if x != nil {
		return x.AllocationId
	}
	return ""
}

func (x *AllocationStatus) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *AllocationStatus) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AllocationStatus) GetDesiredSpecRevision() int64 {
	if x != nil {
		return x.DesiredSpecRevision
	}
	return 0
}

func (x *AllocationStatus) GetAppliedSpecRevision() int64 {
	if x != nil {
		return x.AppliedSpecRevision
	}
	return 0
}

func (x *AllocationStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *AllocationStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AllocationStatus) GetEndpointAddr() string {
	if x != nil {
		return x.EndpointAddr
	}
	return ""
}

func (x *AllocationStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *AllocationStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AllocationStatus) GetDesiredRolloutGeneration() int64 {
	if x != nil {
		return x.DesiredRolloutGeneration
	}
	return 0
}

func (x *AllocationStatus) GetAppliedRolloutGeneration() int64 {
	if x != nil {
		return x.AppliedRolloutGeneration
	}
	return 0
}

type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Allocation    *AllocationStatus      `protobuf:"bytes,2,opt,name=allocation,proto3" json:"allocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_platform_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceStatus) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceStatus) GetAllocation() *AllocationStatus {
	if x != nil {
		return x.Allocation
	}
	return nil
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_platform_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{10}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnsurePrincipalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsurePrincipalRequest) Reset() {
	*x = EnsurePrincipalRequest{}
	mi := &file_platform_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsurePrincipalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsurePrincipalRequest) ProtoMessage() {}

func (x *EnsurePrincipalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsurePrincipalRequest.ProtoReflect.Descriptor instead.
func (*EnsurePrincipalRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{11}
}

func (x *EnsurePrincipalRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EnsurePrincipalRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_platform_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{12}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_platform_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{13}
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CreateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Service       *ServiceInput          `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_platform_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{14}
}

func (x *CreateServiceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateServiceRequest) GetService() *ServiceInput {
	if x != nil {
		return x.Service
	}
	return nil
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Service       *ServiceUpdate         `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_platform_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateServiceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UpdateServiceRequest) GetService() *ServiceUpdate {
	if x != nil {
		return x.Service
	}
	return nil
}

type RedeployServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeployServiceRequest) Reset() {
	*x = RedeployServiceRequest{}
	mi := &file_platform_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeployServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeployServiceRequest) ProtoMessage() {}

func (x *RedeployServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeployServiceRequest.ProtoReflect.Descriptor instead.
func (*RedeployServiceRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{16}
}

func (x *RedeployServiceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RedeployServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_platform_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteServiceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_platform_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{18}
}

func (x *GetServiceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_platform_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{19}
}

func (x *ListServicesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_platform_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{20}
}

func (x *ListServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type CreateVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_platform_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{21}
}

func (x *CreateVolumeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type DeleteVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	VolumeId      string                 `protobuf:"bytes,2,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeRequest) Reset() {
	*x = DeleteVolumeRequest{}
	mi := &file_platform_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeRequest) ProtoMessage() {}

func (x *DeleteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteVolumeRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type ListVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesRequest) Reset() {
	*x = ListVolumesRequest{}
	mi := &file_platform_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesRequest) ProtoMessage() {}

func (x *ListVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListVolumesRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{23}
}

func (x *ListVolumesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*Volume              `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesResponse) Reset() {
	*x = ListVolumesResponse{}
	mi := &file_platform_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesResponse) ProtoMessage() {}

func (x *ListVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListVolumesResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{24}
}

func (x *ListVolumesResponse) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type ServiceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *ServiceSpec           `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInput) Reset() {
	*x = ServiceInput{}
	mi := &file_platform_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInput) ProtoMessage() {}

func (x *ServiceInput) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInput.ProtoReflect.Descriptor instead.
func (*ServiceInput) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{25}
}

func (x *ServiceInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInput) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ServiceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ServiceSpec           `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUpdate) Reset() {
	*x = ServiceUpdate{}
	mi := &file_platform_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdate) ProtoMessage() {}

func (x *ServiceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdate.ProtoReflect.Descriptor instead.
func (*ServiceUpdate) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{26}
}

func (x *ServiceUpdate) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DomainBindingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainBindingInput) Reset() {
	*x = DomainBindingInput{}
	mi := &file_platform_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainBindingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainBindingInput) ProtoMessage() {}

func (x *DomainBindingInput) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainBindingInput.ProtoReflect.Descriptor instead.
func (*DomainBindingInput) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{27}
}

func (x *DomainBindingInput) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DomainBindingInput) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DomainBindingTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainBindingTarget) Reset() {
	*x = DomainBindingTarget{}
	mi := &file_platform_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainBindingTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainBindingTarget) ProtoMessage() {}

func (x *DomainBindingTarget) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainBindingTarget.ProtoReflect.Descriptor instead.
func (*DomainBindingTarget) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{28}
}

func (x *DomainBindingTarget) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type CreateDomainBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Binding       *DomainBindingInput    `protobuf:"bytes,2,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDomainBindingRequest) Reset() {
	*x = CreateDomainBindingRequest{}
	mi := &file_platform_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDomainBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomainBindingRequest) ProtoMessage() {}

func (x *CreateDomainBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomainBindingRequest.ProtoReflect.Descriptor instead.
func (*CreateDomainBindingRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{29}
}

func (x *CreateDomainBindingRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateDomainBindingRequest) GetBinding() *DomainBindingInput {
	if x != nil {
		return x.Binding
	}
	return nil
}

type GetDomainBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainBindingRequest) Reset() {
	*x = GetDomainBindingRequest{}
	mi := &file_platform_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainBindingRequest) ProtoMessage() {}

func (x *GetDomainBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainBindingRequest.ProtoReflect.Descriptor instead.
func (*GetDomainBindingRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{30}
}

func (x *GetDomainBindingRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetDomainBindingRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ListDomainBindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainBindingsRequest) Reset() {
	*x = ListDomainBindingsRequest{}
	mi := &file_platform_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainBindingsRequest) ProtoMessage() {}

func (x *ListDomainBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainBindingsRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{31}
}

func (x *ListDomainBindingsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListDomainBindingsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ListDomainBindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*DomainBinding       `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainBindingsResponse) Reset() {
	*x = ListDomainBindingsResponse{}
	mi := &file_platform_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainBindingsResponse) ProtoMessage() {}

func (x *ListDomainBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainBindingsResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{32}
}

func (x *ListDomainBindingsResponse) GetBindings() []*DomainBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type UpdateDomainBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Binding       *DomainBindingTarget   `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDomainBindingRequest) Reset() {
	*x = UpdateDomainBindingRequest{}
	mi := &file_platform_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDomainBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDomainBindingRequest) ProtoMessage() {}

func (x *UpdateDomainBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDomainBindingRequest.ProtoReflect.Descriptor instead.
func (*UpdateDomainBindingRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateDomainBindingRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateDomainBindingRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *UpdateDomainBindingRequest) GetBinding() *DomainBindingTarget {
	if x != nil {
		return x.Binding
	}
	return nil
}

type DeleteDomainBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainBindingRequest) Reset() {
	*x = DeleteDomainBindingRequest{}
	mi := &file_platform_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainBindingRequest) ProtoMessage() {}

func (x *DeleteDomainBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainBindingRequest.ProtoReflect.Descriptor instead.
func (*DeleteDomainBindingRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteDomainBindingRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteDomainBindingRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetServiceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatusRequest) Reset() {
	*x = GetServiceStatusRequest{}
	mi := &file_platform_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusRequest) ProtoMessage() {}

func (x *GetServiceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetServiceStatusRequest) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{35}
}

func (x *GetServiceStatusRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetServiceStatusRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_platform_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{36}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

var File_platform_proto protoreflect.FileDescriptor

const file_platform_proto_rawDesc = "" +
	"\n" +
	"\x0eplatform.proto\x12\vplatform.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12,\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x18.platform.v1.ProjectKindR\x04kind\x12\x1d\n" +
	"\n" +
	"system_key\x18\x05 \x01(\tR\tsystemKey\"v\n" +
	"\tPrincipal\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf7\x01\n" +
	"\vHealthCheck\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.platform.v1.HealthCheck.TypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x05R\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"9\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_HTTP\x10\x01\x12\f\n" +
	"\bTYPE_TCP\x10\x02\"\x8d\x03\n" +
	"\vServiceSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x123\n" +
	"\x03env\x18\x04 \x03(\v2!.platform.v1.ServiceSpec.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x05 \x01(\x03R\tcpuMillis\x12)\n" +
	"\x10memory_mebibytes\x18\x06 \x01(\x03R\x0fmemoryMebibytes\x12%\n" +
	"\x0econtainer_port\x18\a \x01(\x05R\rcontainerPort\x12;\n" +
	"\fhealth_check\x18\b \x01(\v2\x18.platform.v1.HealthCheckR\vhealthCheck\x12\x1f\n" +
	"\vvolume_name\x18\t \x01(\tR\n" +
	"volumeName\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x02\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12,\n" +
	"\x04spec\x18\x04 \x01(\v2\x18.platform.v1.ServiceSpecR\x04spec\x12#\n" +
	"\rspec_revision\x18\x05 \x01(\x03R\fspecRevision\x12,\n" +
	"\x12allocated_agent_id\x18\x06 \x01(\tR\x10allocatedAgentId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12-\n" +
	"\x12rollout_generation\x18\n" +
	" \x01(\x03R\x11rolloutGeneration\"\xdf\x01\n" +
	"\rDomainBinding\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcb\x01\n" +
	"\x06Volume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12$\n" +
	"\x0ebound_agent_id\x18\x05 \x01(\tR\fboundAgentId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x96\x02\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eadvertise_addr\x18\x03 \x01(\tR\radvertiseAddr\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x12.\n" +
	"\x13cpu_millis_capacity\x18\x05 \x01(\x03R\x11cpuMillisCapacity\x12:\n" +
	"\x19memory_mebibytes_capacity\x18\x06 \x01(\x03R\x17memoryMebibytesCapacity\x12<\n" +
	"\flast_seen_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"\xff\x03\n" +
	"\x10AllocationStatus\x12#\n" +
	"\rallocation_id\x18\x01 \x01(\tR\fallocationId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x122\n" +
	"\x15desired_spec_revision\x18\x04 \x01(\x03R\x13desiredSpecRevision\x122\n" +
	"\x15applied_spec_revision\x18\x05 \x01(\x03R\x13appliedSpecRevision\x12\x14\n" +
	"\x05phase\x18\x06 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12#\n" +
	"\rendpoint_addr\x18\b \x01(\tR\fendpointAddr\x12\x18\n" +
	"\ahealthy\x18\t \x01(\bR\ahealthy\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\x1adesired_rollout_generation\x18\v \x01(\x03R\x18desiredRolloutGeneration\x12<\n" +
	"\x1aapplied_rollout_generation\x18\f \x01(\x03R\x18appliedRolloutGeneration\"~\n" +
	"\rServiceStatus\x12.\n" +
	"\aservice\x18\x01 \x01(\v2\x14.platform.v1.ServiceR\aservice\x12=\n" +
	"\n" +
	"allocation\x18\x02 \x01(\v2\x1d.platform.v1.AllocationStatusR\n" +
	"allocation\"*\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x16EnsurePrincipalRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"H\n" +
	"\x14ListProjectsResponse\x120\n" +
	"\bprojects\x18\x01 \x03(\v2\x14.platform.v1.ProjectR\bprojects\"2\n" +
	"\x11GetProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"j\n" +
	"\x14CreateServiceRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x123\n" +
	"\aservice\x18\x02 \x01(\v2\x19.platform.v1.ServiceInputR\aservice\"\x8a\x01\n" +
	"\x14UpdateServiceRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x124\n" +
	"\aservice\x18\x03 \x01(\v2\x1a.platform.v1.ServiceUpdateR\aservice\"V\n" +
	"\x16RedeployServiceRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"T\n" +
	"\x14DeleteServiceRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"Q\n" +
	"\x11GetServiceRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"4\n" +
	"\x13ListServicesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"H\n" +
	"\x14ListServicesResponse\x120\n" +
	"\bservices\x18\x01 \x03(\v2\x14.platform.v1.ServiceR\bservices\"g\n" +
	"\x13CreateVolumeRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"Q\n" +
	"\x13DeleteVolumeRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tvolume_id\x18\x02 \x01(\tR\bvolumeId\"3\n" +
	"\x12ListVolumesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"D\n" +
	"\x13ListVolumesResponse\x12-\n" +
	"\avolumes\x18\x01 \x03(\v2\x13.platform.v1.VolumeR\avolumes\"P\n" +
	"\fServiceInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x04spec\x18\x02 \x01(\v2\x18.platform.v1.ServiceSpecR\x04spec\"=\n" +
	"\rServiceUpdate\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.platform.v1.ServiceSpecR\x04spec\"O\n" +
	"\x12DomainBindingInput\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"4\n" +
	"\x13DomainBindingTarget\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"v\n" +
	"\x1aCreateDomainBindingRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x129\n" +
	"\abinding\x18\x02 \x01(\v2\x1f.platform.v1.DomainBindingInputR\abinding\"T\n" +
	"\x17GetDomainBindingRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"Y\n" +
	"\x19ListDomainBindingsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"T\n" +
	"\x1aListDomainBindingsResponse\x126\n" +
	"\bbindings\x18\x01 \x03(\v2\x1a.platform.v1.DomainBindingR\bbindings\"\x93\x01\n" +
	"\x1aUpdateDomainBindingRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12:\n" +
	"\abinding\x18\x03 \x01(\v2 .platform.v1.DomainBindingTargetR\abinding\"W\n" +
	"\x1aDeleteDomainBindingRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"W\n" +
	"\x17GetServiceStatusRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"@\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x06agents\x18\x01 \x03(\v2\x12.platform.v1.AgentR\x06agents*\\\n" +
	"\vProjectKind\x12\x1c\n" +
	"\x18PROJECT_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PROJECT_KIND_USER\x10\x01\x12\x18\n" +
	"\x14PROJECT_KIND_MANAGED\x10\x022\x98\x14\n" +
	"\x0fPlatformService\x12o\n" +
	"\x0fEnsurePrincipal\x12#.platform.v1.EnsurePrincipalRequest\x1a\x16.platform.v1.Principal\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/principal:ensure\x12a\n" +
	"\rCreateProject\x12!.platform.v1.CreateProjectRequest\x1a\x14.platform.v1.Project\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/projects\x12_\n" +
	"\fListProjects\x12\x16.google.protobuf.Empty\x1a!.platform.v1.ListProjectsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/projects\x12e\n" +
	"\n" +
	"GetProject\x12\x1e.platform.v1.GetProjectRequest\x1a\x14.platform.v1.Project\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/projects/{project_id}\x12}\n" +
	"\rCreateService\x12!.platform.v1.CreateServiceRequest\x1a\x14.platform.v1.Service\"3\x82\xd3\xe4\x93\x02-:\aservice\"\"/v1/projects/{project_id}/services\x12\x8a\x01\n" +
	"\rUpdateService\x12!.platform.v1.UpdateServiceRequest\x1a\x14.platform.v1.Service\"@\x82\xd3\xe4\x93\x02::\aservice\x1a//v1/projects/{project_id}/services/{service_id}\x12\x97\x01\n" +
	"\x0fRedeployService\x12#.platform.v1.RedeployServiceRequest\x1a\x1a.platform.v1.ServiceStatus\"C\x82\xd3\xe4\x93\x02=:\x01*\"8/v1/projects/{project_id}/services/{service_id}:redeploy\x12\x83\x01\n" +
	"\rDeleteService\x12!.platform.v1.DeleteServiceRequest\x1a\x16.google.protobuf.Empty\"7\x82\xd3\xe4\x93\x021*//v1/projects/{project_id}/services/{service_id}\x12{\n" +
	"\n" +
	"GetService\x12\x1e.platform.v1.GetServiceRequest\x1a\x14.platform.v1.Service\"7\x82\xd3\xe4\x93\x021\x12//v1/projects/{project_id}/services/{service_id}\x12\x7f\n" +
	"\fListServices\x12 .platform.v1.ListServicesRequest\x1a!.platform.v1.ListServicesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/projects/{project_id}/services\x12s\n" +
	"\fCreateVolume\x12 .platform.v1.CreateVolumeRequest\x1a\x13.platform.v1.Volume\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/projects/{project_id}/volumes\x12\x7f\n" +
	"\fDeleteVolume\x12 .platform.v1.DeleteVolumeRequest\x1a\x16.google.protobuf.Empty\"5\x82\xd3\xe4\x93\x02/*-/v1/projects/{project_id}/volumes/{volume_id}\x12{\n" +
	"\vListVolumes\x12\x1f.platform.v1.ListVolumesRequest\x1a .platform.v1.ListVolumesResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/projects/{project_id}/volumes\x12\x8e\x01\n" +
	"\x13CreateDomainBinding\x12'.platform.v1.CreateDomainBindingRequest\x1a\x1a.platform.v1.DomainBinding\"2\x82\xd3\xe4\x93\x02,:\abinding\"!/v1/projects/{project_id}/domains\x12\x8a\x01\n" +
	"\x10GetDomainBinding\x12$.platform.v1.GetDomainBindingRequest\x1a\x1a.platform.v1.DomainBinding\"4\x82\xd3\xe4\x93\x02.\x12,/v1/projects/{project_id}/domains/{hostname}\x12\x90\x01\n" +
	"\x12ListDomainBindings\x12&.platform.v1.ListDomainBindingsRequest\x1a'.platform.v1.ListDomainBindingsResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/projects/{project_id}/domains\x12\x99\x01\n" +
	"\x13UpdateDomainBinding\x12'.platform.v1.UpdateDomainBindingRequest\x1a\x1a.platform.v1.DomainBinding\"=\x82\xd3\xe4\x93\x027:\abinding\x1a,/v1/projects/{project_id}/domains/{hostname}\x12\x8c\x01\n" +
	"\x13DeleteDomainBinding\x12'.platform.v1.DeleteDomainBindingRequest\x1a\x16.google.protobuf.Empty\"4\x82\xd3\xe4\x93\x02.*,/v1/projects/{project_id}/domains/{hostname}\x12\x94\x01\n" +
	"\x10GetServiceStatus\x12$.platform.v1.GetServiceStatusRequest\x1a\x1a.platform.v1.ServiceStatus\">\x82\xd3\xe4\x93\x028\x126/v1/projects/{project_id}/services/{service_id}/status\x12Y\n" +
	"\n" +
	"ListAgents\x12\x16.google.protobuf.Empty\x1a\x1f.platform.v1.ListAgentsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/agentsB.Z,ebof-wg-mesh/api/proto/platformv1;platformv1b\x06proto3"

var (
	file_platform_proto_rawDescOnce sync.Once
	file_platform_proto_rawDescData []byte
)

func file_platform_proto_rawDescGZIP() []byte {
	file_platform_proto_rawDescOnce.Do(func() {
		file_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_proto_rawDesc), len(file_platform_proto_rawDesc)))
	})
	return file_platform_proto_rawDescData
}

var file_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_platform_proto_goTypes = []any{
	(ProjectKind)(0),                   // 0: platform.v1.ProjectKind
	(HealthCheck_Type)(0),              // 1: platform.v1.HealthCheck.Type
	(*Project)(nil),                    // 2: platform.v1.Project
	(*Principal)(nil),                  // 3: platform.v1.Principal
	(*HealthCheck)(nil),                // 4: platform.v1.HealthCheck
	(*ServiceSpec)(nil),                // 5: platform.v1.ServiceSpec
	(*Service)(nil),                    // 6: platform.v1.Service
	(*DomainBinding)(nil),              // 7: platform.v1.DomainBinding
	(*Volume)(nil),                     // 8: platform.v1.Volume
	(*Agent)(nil),                      // 9: platform.v1.Agent
	(*AllocationStatus)(nil),           // 10: platform.v1.AllocationStatus
	(*ServiceStatus)(nil),              // 11: platform.v1.ServiceStatus
	(*CreateProjectRequest)(nil),       // 12: platform.v1.CreateProjectRequest
	(*EnsurePrincipalRequest)(nil),     // 13: platform.v1.EnsurePrincipalRequest
	(*ListProjectsResponse)(nil),       // 14: platform.v1.ListProjectsResponse
	(*GetProjectRequest)(nil),          // 15: platform.v1.GetProjectRequest
	(*CreateServiceRequest)(nil),       // 16: platform.v1.CreateServiceRequest
	(*UpdateServiceRequest)(nil),       // 17: platform.v1.UpdateServiceRequest
	(*RedeployServiceRequest)(nil),     // 18: platform.v1.RedeployServiceRequest
	(*DeleteServiceRequest)(nil),       // 19: platform.v1.DeleteServiceRequest
	(*GetServiceRequest)(nil),          // 20: platform.v1.GetServiceRequest
	(*ListServicesRequest)(nil),        // 21: platform.v1.ListServicesRequest
	(*ListServicesResponse)(nil),       // 22: platform.v1.ListServicesResponse
	(*CreateVolumeRequest)(nil),        // 23: platform.v1.CreateVolumeRequest
	(*DeleteVolumeRequest)(nil),        // 24: platform.v1.DeleteVolumeRequest
	(*ListVolumesRequest)(nil),         // 25: platform.v1.ListVolumesRequest
	(*ListVolumesResponse)(nil),        // 26: platform.v1.ListVolumesResponse
	(*ServiceInput)(nil),               // 27: platform.v1.ServiceInput
	(*ServiceUpdate)(nil),              // 28: platform.v1.ServiceUpdate
	(*DomainBindingInput)(nil),         // 29: platform.v1.DomainBindingInput
	(*DomainBindingTarget)(nil),        // 30: platform.v1.DomainBindingTarget
	(*CreateDomainBindingRequest)(nil), // 31: platform.v1.CreateDomainBindingRequest
	(*GetDomainBindingRequest)(nil),    // 32: platform.v1.GetDomainBindingRequest
	(*ListDomainBindingsRequest)(nil),  // 33: platform.v1.ListDomainBindingsRequest
	(*ListDomainBindingsResponse)(nil), // 34: platform.v1.ListDomainBindingsResponse
	(*UpdateDomainBindingRequest)(nil), // 35: platform.v1.UpdateDomainBindingRequest
	(*DeleteDomainBindingRequest)(nil), // 36: platform.v1.DeleteDomainBindingRequest
	(*GetServiceStatusRequest)(nil),    // 37: platform.v1.GetServiceStatusRequest
	(*ListAgentsResponse)(nil),         // 38: platform.v1.ListAgentsResponse
	nil,                                // 39: platform.v1.ServiceSpec.EnvEntry
	(*timestamppb.Timestamp)(nil),      // 40: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 41: google.protobuf.Empty
}
var file_platform_proto_depIdxs = []int32{
	40, // 0: platform.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: platform.v1.Project.kind:type_name -> platform.v1.ProjectKind
	40, // 2: platform.v1.Principal.created_at:type_name -> google.protobuf.Timestamp
	1,  // 3: platform.v1.HealthCheck.type:type_name -> platform.v1.HealthCheck.Type
	39, // 4: platform.v1.ServiceSpec.env:type_name -> platform.v1.ServiceSpec.EnvEntry
	4,  // 5: platform.v1.ServiceSpec.health_check:type_name -> platform.v1.HealthCheck
	5,  // 6: platform.v1.Service.spec:type_name -> platform.v1.ServiceSpec
	40, // 7: platform.v1.Service.created_at:type_name -> google.protobuf.Timestamp
	40, // 8: platform.v1.Service.updated_at:type_name -> google.protobuf.Timestamp
	40, // 9: platform.v1.DomainBinding.created_at:type_name -> google.protobuf.Timestamp
	40, // 10: platform.v1.DomainBinding.updated_at:type_name -> google.protobuf.Timestamp
	40, // 11: platform.v1.Volume.created_at:type_name -> google.protobuf.Timestamp
	40, // 12: platform.v1.Agent.last_seen_at:type_name -> google.protobuf.Timestamp
	40, // 13: platform.v1.AllocationStatus.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 14: platform.v1.ServiceStatus.service:type_name -> platform.v1.Service
	10, // 15: platform.v1.ServiceStatus.allocation:type_name -> platform.v1.AllocationStatus
	2,  // 16: platform.v1.ListProjectsResponse.projects:type_name -> platform.v1.Project
	27, // 17: platform.v1.CreateServiceRequest.service:type_name -> platform.v1.ServiceInput
	28, // 18: platform.v1.UpdateServiceRequest.service:type_name -> platform.v1.ServiceUpdate
	6,  // 19: platform.v1.ListServicesResponse.services:type_name -> platform.v1.Service
	8,  // 20: platform.v1.ListVolumesResponse.volumes:type_name -> platform.v1.Volume
	5,  // 21: platform.v1.ServiceInput.spec:type_name -> platform.v1.ServiceSpec
	5,  // 22: platform.v1.ServiceUpdate.spec:type_name -> platform.v1.ServiceSpec
	29, // 23: platform.v1.CreateDomainBindingRequest.binding:type_name -> platform.v1.DomainBindingInput
	7,  // 24: platform.v1.ListDomainBindingsResponse.bindings:type_name -> platform.v1.DomainBinding
	30, // 25: platform.v1.UpdateDomainBindingRequest.binding:type_name -> platform.v1.DomainBindingTarget
	9,  // 26: platform.v1.ListAgentsResponse.agents:type_name -> platform.v1.Agent
	13, // 27: platform.v1.PlatformService.EnsurePrincipal:input_type -> platform.v1.EnsurePrincipalRequest
	12, // 28: platform.v1.PlatformService.CreateProject:input_type -> platform.v1.CreateProjectRequest
	41, // 29: platform.v1.PlatformService.ListProjects:input_type -> google.protobuf.Empty
	15, // 30: platform.v1.PlatformService.GetProject:input_type -> platform.v1.GetProjectRequest
	16, // 31: platform.v1.PlatformService.CreateService:input_type -> platform.v1.CreateServiceRequest
	17, // 32: platform.v1.PlatformService.UpdateService:input_type -> platform.v1.UpdateServiceRequest
	18, // 33: platform.v1.PlatformService.RedeployService:input_type -> platform.v1.RedeployServiceRequest
	19, // 34: platform.v1.PlatformService.DeleteService:input_type -> platform.v1.DeleteServiceRequest
	20, // 35: platform.v1.PlatformService.GetService:input_type -> platform.v1.GetServiceRequest
	21, // 36: platform.v1.PlatformService.ListServices:input_type -> platform.v1.ListServicesRequest
	23, // 37: platform.v1.PlatformService.CreateVolume:input_type -> platform.v1.CreateVolumeRequest
	24, // 38: platform.v1.PlatformService.DeleteVolume:input_type -> platform.v1.DeleteVolumeRequest
	25, // 39: platform.v1.PlatformService.ListVolumes:input_type -> platform.v1.ListVolumesRequest
	31, // 40: platform.v1.PlatformService.CreateDomainBinding:input_type -> platform.v1.CreateDomainBindingRequest
	32, // 41: platform.v1.PlatformService.GetDomainBinding:input_type -> platform.v1.GetDomainBindingRequest
	33, // 42: platform.v1.PlatformService.ListDomainBindings:input_type -> platform.v1.ListDomainBindingsRequest
	35, // 43: platform.v1.PlatformService.UpdateDomainBinding:input_type -> platform.v1.UpdateDomainBindingRequest
	36, // 44: platform.v1.PlatformService.DeleteDomainBinding:input_type -> platform.v1.DeleteDomainBindingRequest
	37, // 45: platform.v1.PlatformService.GetServiceStatus:input_type -> platform.v1.GetServiceStatusRequest
	41, // 46: platform.v1.PlatformService.ListAgents:input_type -> google.protobuf.Empty
	3,  // 47: platform.v1.PlatformService.EnsurePrincipal:output_type -> platform.v1.Principal
	2,  // 48: platform.v1.PlatformService.CreateProject:output_type -> platform.v1.Project
	14, // 49: platform.v1.PlatformService.ListProjects:output_type -> platform.v1.ListProjectsResponse
	2,  // 50: platform.v1.PlatformService.GetProject:output_type -> platform.v1.Project
	6,  // 51: platform.v1.PlatformService.CreateService:output_type -> platform.v1.Service
	6,  // 52: platform.v1.PlatformService.UpdateService:output_type -> platform.v1.Service
	11, // 53: platform.v1.PlatformService.RedeployService:output_type -> platform.v1.ServiceStatus
	41, // 54: platform.v1.PlatformService.DeleteService:output_type -> google.protobuf.Empty
	6,  // 55: platform.v1.PlatformService.GetService:output_type -> platform.v1.Service
	22, // 56: platform.v1.PlatformService.ListServices:output_type -> platform.v1.ListServicesResponse
	8,  // 57: platform.v1.PlatformService.CreateVolume:output_type -> platform.v1.Volume
	41, // 58: platform.v1.PlatformService.DeleteVolume:output_type -> google.protobuf.Empty
	26, // 59: platform.v1.PlatformService.ListVolumes:output_type -> platform.v1.ListVolumesResponse
	7,  // 60: platform.v1.PlatformService.CreateDomainBinding:output_type -> platform.v1.DomainBinding
	7,  // 61: platform.v1.PlatformService.GetDomainBinding:output_type -> platform.v1.DomainBinding
	34, // 62: platform.v1.PlatformService.ListDomainBindings:output_type -> platform.v1.ListDomainBindingsResponse
	7,  // 63: platform.v1.PlatformService.UpdateDomainBinding:output_type -> platform.v1.DomainBinding
	41, // 64: platform.v1.PlatformService.DeleteDomainBinding:output_type -> google.protobuf.Empty
	11, // 65: platform.v1.PlatformService.GetServiceStatus:output_type -> platform.v1.ServiceStatus
	38, // 66: platform.v1.PlatformService.ListAgents:output_type -> platform.v1.ListAgentsResponse
	47, // [47:67] is the sub-list for method output_type
	27, // [27:47] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_platform_proto_init() }
func file_platform_proto_init() {
	if File_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_proto_rawDesc), len(file_platform_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_proto_goTypes,
		DependencyIndexes: file_platform_proto_depIdxs,
		EnumInfos:         file_platform_proto_enumTypes,
		MessageInfos:      file_platform_proto_msgTypes,
	}.Build()
	File_platform_proto = out.File
	file_platform_proto_goTypes = nil
	file_platform_proto_depIdxs = nil
}
