// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: platform.proto

package platformv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformService_CreateProject_FullMethodName          = "/platform.v1.PlatformService/CreateProject"
	PlatformService_ListProjects_FullMethodName           = "/platform.v1.PlatformService/ListProjects"
	PlatformService_GetProject_FullMethodName             = "/platform.v1.PlatformService/GetProject"
	PlatformService_ListEnvironments_FullMethodName       = "/platform.v1.PlatformService/ListEnvironments"
	PlatformService_GetEnvironment_FullMethodName         = "/platform.v1.PlatformService/GetEnvironment"
	PlatformService_CreateEnvironment_FullMethodName      = "/platform.v1.PlatformService/CreateEnvironment"
	PlatformService_DuplicateEnvironment_FullMethodName   = "/platform.v1.PlatformService/DuplicateEnvironment"
	PlatformService_RenameEnvironment_FullMethodName      = "/platform.v1.PlatformService/RenameEnvironment"
	PlatformService_DeleteEnvironment_FullMethodName      = "/platform.v1.PlatformService/DeleteEnvironment"
	PlatformService_DeployEnvironment_FullMethodName      = "/platform.v1.PlatformService/DeployEnvironment"
	PlatformService_LinkGitHubRepository_FullMethodName   = "/platform.v1.PlatformService/LinkGitHubRepository"
	PlatformService_InspectSource_FullMethodName          = "/platform.v1.PlatformService/InspectSource"
	PlatformService_CreateService_FullMethodName          = "/platform.v1.PlatformService/CreateService"
	PlatformService_UpdateService_FullMethodName          = "/platform.v1.PlatformService/UpdateService"
	PlatformService_ScaleService_FullMethodName           = "/platform.v1.PlatformService/ScaleService"
	PlatformService_ApplyDeploymentAction_FullMethodName  = "/platform.v1.PlatformService/ApplyDeploymentAction"
	PlatformService_DiscardServiceChanges_FullMethodName  = "/platform.v1.PlatformService/DiscardServiceChanges"
	PlatformService_DeleteService_FullMethodName          = "/platform.v1.PlatformService/DeleteService"
	PlatformService_GetService_FullMethodName             = "/platform.v1.PlatformService/GetService"
	PlatformService_ListServices_FullMethodName           = "/platform.v1.PlatformService/ListServices"
	PlatformService_CreateVolume_FullMethodName           = "/platform.v1.PlatformService/CreateVolume"
	PlatformService_DeleteVolume_FullMethodName           = "/platform.v1.PlatformService/DeleteVolume"
	PlatformService_ListVolumes_FullMethodName            = "/platform.v1.PlatformService/ListVolumes"
	PlatformService_CreateDomainBinding_FullMethodName    = "/platform.v1.PlatformService/CreateDomainBinding"
	PlatformService_GenerateDomainBinding_FullMethodName  = "/platform.v1.PlatformService/GenerateDomainBinding"
	PlatformService_GetDomainBinding_FullMethodName       = "/platform.v1.PlatformService/GetDomainBinding"
	PlatformService_ListDomainBindings_FullMethodName     = "/platform.v1.PlatformService/ListDomainBindings"
	PlatformService_UpdateDomainBinding_FullMethodName    = "/platform.v1.PlatformService/UpdateDomainBinding"
	PlatformService_DeleteDomainBinding_FullMethodName    = "/platform.v1.PlatformService/DeleteDomainBinding"
	PlatformService_GetServiceStatus_FullMethodName       = "/platform.v1.PlatformService/GetServiceStatus"
	PlatformService_ListServiceLogs_FullMethodName        = "/platform.v1.PlatformService/ListServiceLogs"
	PlatformService_ListServiceDeployments_FullMethodName = "/platform.v1.PlatformService/ListServiceDeployments"
	PlatformService_ListAgents_FullMethodName             = "/platform.v1.PlatformService/ListAgents"
	PlatformService_ListSandboxProfiles_FullMethodName    = "/platform.v1.PlatformService/ListSandboxProfiles"
)

// PlatformServiceClient is the client API for PlatformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatformServiceClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error)
	ListProjects(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error)
	ListEnvironments(ctx context.Context, in *ListEnvironmentsRequest, opts ...grpc.CallOption) (*ListEnvironmentsResponse, error)
	GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error)
	CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error)
	DuplicateEnvironment(ctx context.Context, in *DuplicateEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error)
	RenameEnvironment(ctx context.Context, in *RenameEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error)
	DeleteEnvironment(ctx context.Context, in *DeleteEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeployEnvironment(ctx context.Context, in *DeployEnvironmentRequest, opts ...grpc.CallOption) (*DeployEnvironmentResponse, error)
	LinkGitHubRepository(ctx context.Context, in *LinkGitHubRepositoryRequest, opts ...grpc.CallOption) (*InspectSourceResponse, error)
	InspectSource(ctx context.Context, in *InspectSourceRequest, opts ...grpc.CallOption) (*InspectSourceResponse, error)
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*Service, error)
	UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*Service, error)
	ScaleService(ctx context.Context, in *ScaleServiceRequest, opts ...grpc.CallOption) (*ServiceStatus, error)
	ApplyDeploymentAction(ctx context.Context, in *ApplyDeploymentActionRequest, opts ...grpc.CallOption) (*ServiceStatus, error)
	DiscardServiceChanges(ctx context.Context, in *DiscardServiceChangesRequest, opts ...grpc.CallOption) (*Service, error)
	DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*Volume, error)
	DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	CreateDomainBinding(ctx context.Context, in *CreateDomainBindingRequest, opts ...grpc.CallOption) (*DomainBinding, error)
	GenerateDomainBinding(ctx context.Context, in *GenerateDomainBindingRequest, opts ...grpc.CallOption) (*DomainBinding, error)
	GetDomainBinding(ctx context.Context, in *GetDomainBindingRequest, opts ...grpc.CallOption) (*DomainBinding, error)
	ListDomainBindings(ctx context.Context, in *ListDomainBindingsRequest, opts ...grpc.CallOption) (*ListDomainBindingsResponse, error)
	UpdateDomainBinding(ctx context.Context, in *UpdateDomainBindingRequest, opts ...grpc.CallOption) (*DomainBinding, error)
	DeleteDomainBinding(ctx context.Context, in *DeleteDomainBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetServiceStatus(ctx context.Context, in *GetServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatus, error)
	ListServiceLogs(ctx context.Context, in *ListServiceLogsRequest, opts ...grpc.CallOption) (*ListServiceLogsResponse, error)
	ListServiceDeployments(ctx context.Context, in *ListServiceDeploymentsRequest, opts ...grpc.CallOption) (*ListServiceDeploymentsResponse, error)
	ListAgents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	ListSandboxProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSandboxProfilesResponse, error)
}

type platformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformServiceClient(cc grpc.ClientConnInterface) PlatformServiceClient {
	return &platformServiceClient{cc}
}

func (c *platformServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, PlatformService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListProjects(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, PlatformService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListEnvironments(ctx context.Context, in *ListEnvironmentsRequest, opts ...grpc.CallOption) (*ListEnvironmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnvironmentsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListEnvironments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Environment)
	err := c.cc.Invoke(ctx, PlatformService_GetEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Environment)
	err := c.cc.Invoke(ctx, PlatformService_CreateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) DuplicateEnvironment(ctx context.Context, in *DuplicateEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Environment)
	err := c.cc.Invoke(ctx, PlatformService_DuplicateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) RenameEnvironment(ctx context.Context, in *RenameEnvironmentRequest, opts ...grpc.CallOption) (*Environment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Environment)
	err := c.cc.Invoke(ctx, PlatformService_RenameEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) DeleteEnvironment(ctx context.Context, in *DeleteEnvironmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlatformService_DeleteEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) DeployEnvironment(ctx context.Context, in *DeployEnvironmentRequest, opts ...grpc.CallOption) (*DeployEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployEnvironmentResponse)
	err := c.cc.Invoke(ctx, PlatformService_DeployEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) LinkGitHubRepository(ctx context.Context, in *LinkGitHubRepositoryRequest, opts ...grpc.CallOption) (*InspectSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectSourceResponse)
	err := c.cc.Invoke(ctx, PlatformService_LinkGitHubRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) InspectSource(ctx context.Context, in *InspectSourceRequest, opts ...grpc.CallOption) (*InspectSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectSourceResponse)
	err := c.cc.Invoke(ctx, PlatformService_InspectSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, PlatformService_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, PlatformService_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ScaleService(ctx context.Context, in *ScaleServiceRequest, opts ...grpc.CallOption) (*ServiceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, PlatformService_ScaleService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ApplyDeploymentAction(ctx context.Context, in *ApplyDeploymentActionRequest, opts ...grpc.CallOption) (*ServiceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, PlatformService_ApplyDeploymentAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) DiscardServiceChanges(ctx context.Context, in *DiscardServiceChangesRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, PlatformService_DiscardServiceChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlatformService_DeleteService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, PlatformService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*Volume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volume)
	err := c.cc.Invoke(ctx, PlatformService_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlatformService_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) CreateDomainBinding(ctx context.Context, in *CreateDomainBindingRequest, opts ...grpc.CallOption) (*DomainBinding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainBinding)
	err := c.cc.Invoke(ctx, PlatformService_CreateDomainBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GenerateDomainBinding(ctx context.Context, in *GenerateDomainBindingRequest, opts ...grpc.CallOption) (*DomainBinding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainBinding)
	err := c.cc.Invoke(ctx, PlatformService_GenerateDomainBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetDomainBinding(ctx context.Context, in *GetDomainBindingRequest, opts ...grpc.CallOption) (*DomainBinding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainBinding)
	err := c.cc.Invoke(ctx, PlatformService_GetDomainBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListDomainBindings(ctx context.Context, in *ListDomainBindingsRequest, opts ...grpc.CallOption) (*ListDomainBindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDomainBindingsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListDomainBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) UpdateDomainBinding(ctx context.Context, in *UpdateDomainBindingRequest, opts ...grpc.CallOption) (*DomainBinding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainBinding)
	err := c.cc.Invoke(ctx, PlatformService_UpdateDomainBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) DeleteDomainBinding(ctx context.Context, in *DeleteDomainBindingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlatformService_DeleteDomainBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetServiceStatus(ctx context.Context, in *GetServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, PlatformService_GetServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListServiceLogs(ctx context.Context, in *ListServiceLogsRequest, opts ...grpc.CallOption) (*ListServiceLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceLogsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListServiceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListServiceDeployments(ctx context.Context, in *ListServiceDeploymentsRequest, opts ...grpc.CallOption) (*ListServiceDeploymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceDeploymentsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListServiceDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListAgents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListSandboxProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSandboxProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxProfilesResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListSandboxProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServiceServer is the server API for PlatformService service.
// All implementations must embed UnimplementedPlatformServiceServer
// for forward compatibility.
type PlatformServiceServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	ListProjects(context.Context, *emptypb.Empty) (*ListProjectsResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*Project, error)
	ListEnvironments(context.Context, *ListEnvironmentsRequest) (*ListEnvironmentsResponse, error)
	GetEnvironment(context.Context, *GetEnvironmentRequest) (*Environment, error)
	CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*Environment, error)
	DuplicateEnvironment(context.Context, *DuplicateEnvironmentRequest) (*Environment, error)
	RenameEnvironment(context.Context, *RenameEnvironmentRequest) (*Environment, error)
	DeleteEnvironment(context.Context, *DeleteEnvironmentRequest) (*emptypb.Empty, error)
	DeployEnvironment(context.Context, *DeployEnvironmentRequest) (*DeployEnvironmentResponse, error)
	LinkGitHubRepository(context.Context, *LinkGitHubRepositoryRequest) (*InspectSourceResponse, error)
	InspectSource(context.Context, *InspectSourceRequest) (*InspectSourceResponse, error)
	CreateService(context.Context, *CreateServiceRequest) (*Service, error)
	UpdateService(context.Context, *UpdateServiceRequest) (*Service, error)
	ScaleService(context.Context, *ScaleServiceRequest) (*ServiceStatus, error)
	ApplyDeploymentAction(context.Context, *ApplyDeploymentActionRequest) (*ServiceStatus, error)
	DiscardServiceChanges(context.Context, *DiscardServiceChangesRequest) (*Service, error)
	DeleteService(context.Context, *DeleteServiceRequest) (*emptypb.Empty, error)
	GetService(context.Context, *GetServiceRequest) (*Service, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	CreateVolume(context.Context, *CreateVolumeRequest) (*Volume, error)
	DeleteVolume(context.Context, *DeleteVolumeRequest) (*emptypb.Empty, error)
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	CreateDomainBinding(context.Context, *CreateDomainBindingRequest) (*DomainBinding, error)
	GenerateDomainBinding(context.Context, *GenerateDomainBindingRequest) (*DomainBinding, error)
	GetDomainBinding(context.Context, *GetDomainBindingRequest) (*DomainBinding, error)
	ListDomainBindings(context.Context, *ListDomainBindingsRequest) (*ListDomainBindingsResponse, error)
	UpdateDomainBinding(context.Context, *UpdateDomainBindingRequest) (*DomainBinding, error)
	DeleteDomainBinding(context.Context, *DeleteDomainBindingRequest) (*emptypb.Empty, error)
	GetServiceStatus(context.Context, *GetServiceStatusRequest) (*ServiceStatus, error)
	ListServiceLogs(context.Context, *ListServiceLogsRequest) (*ListServiceLogsResponse, error)
	ListServiceDeployments(context.Context, *ListServiceDeploymentsRequest) (*ListServiceDeploymentsResponse, error)
	ListAgents(context.Context, *emptypb.Empty) (*ListAgentsResponse, error)
	ListSandboxProfiles(context.Context, *emptypb.Empty) (*ListSandboxProfilesResponse, error)
	mustEmbedUnimplementedPlatformServiceServer()
}

// UnimplementedPlatformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformServiceServer struct{}

func (UnimplementedPlatformServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedPlatformServiceServer) ListProjects(context.Context, *emptypb.Empty) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedPlatformServiceServer) GetProject(context.Context, *GetProjectRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedPlatformServiceServer) ListEnvironments(context.Context, *ListEnvironmentsRequest) (*ListEnvironmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnvironments not implemented")
}
func (UnimplementedPlatformServiceServer) GetEnvironment(context.Context, *GetEnvironmentRequest) (*Environment, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnvironment not implemented")
}
func (UnimplementedPlatformServiceServer) CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*Environment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnvironment not implemented")
}
func (UnimplementedPlatformServiceServer) DuplicateEnvironment(context.Context, *DuplicateEnvironmentRequest) (*Environment, error) {
	return nil, status.Error(codes.Unimplemented, "method DuplicateEnvironment not implemented")
}
func (UnimplementedPlatformServiceServer) RenameEnvironment(context.Context, *RenameEnvironmentRequest) (*Environment, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameEnvironment not implemented")
}
func (UnimplementedPlatformServiceServer) DeleteEnvironment(context.Context, *DeleteEnvironmentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEnvironment not implemented")
}
func (UnimplementedPlatformServiceServer) DeployEnvironment(context.Context, *DeployEnvironmentRequest) (*DeployEnvironmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployEnvironment not implemented")
}
func (UnimplementedPlatformServiceServer) LinkGitHubRepository(context.Context, *LinkGitHubRepositoryRequest) (*InspectSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkGitHubRepository not implemented")
}
func (UnimplementedPlatformServiceServer) InspectSource(context.Context, *InspectSourceRequest) (*InspectSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectSource not implemented")
}
func (UnimplementedPlatformServiceServer) CreateService(context.Context, *CreateServiceRequest) (*Service, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedPlatformServiceServer) UpdateService(context.Context, *UpdateServiceRequest) (*Service, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedPlatformServiceServer) ScaleService(context.Context, *ScaleServiceRequest) (*ServiceStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ScaleService not implemented")
}
func (UnimplementedPlatformServiceServer) ApplyDeploymentAction(context.Context, *ApplyDeploymentActionRequest) (*ServiceStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyDeploymentAction not implemented")
}
func (UnimplementedPlatformServiceServer) DiscardServiceChanges(context.Context, *DiscardServiceChangesRequest) (*Service, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscardServiceChanges not implemented")
}
func (UnimplementedPlatformServiceServer) DeleteService(context.Context, *DeleteServiceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedPlatformServiceServer) GetService(context.Context, *GetServiceRequest) (*Service, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedPlatformServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedPlatformServiceServer) CreateVolume(context.Context, *CreateVolumeRequest) (*Volume, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedPlatformServiceServer) DeleteVolume(context.Context, *DeleteVolumeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedPlatformServiceServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedPlatformServiceServer) CreateDomainBinding(context.Context, *CreateDomainBindingRequest) (*DomainBinding, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDomainBinding not implemented")
}
func (UnimplementedPlatformServiceServer) GenerateDomainBinding(context.Context, *GenerateDomainBindingRequest) (*DomainBinding, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateDomainBinding not implemented")
}
func (UnimplementedPlatformServiceServer) GetDomainBinding(context.Context, *GetDomainBindingRequest) (*DomainBinding, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomainBinding not implemented")
}
func (UnimplementedPlatformServiceServer) ListDomainBindings(context.Context, *ListDomainBindingsRequest) (*ListDomainBindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDomainBindings not implemented")
}
func (UnimplementedPlatformServiceServer) UpdateDomainBinding(context.Context, *UpdateDomainBindingRequest) (*DomainBinding, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDomainBinding not implemented")
}
func (UnimplementedPlatformServiceServer) DeleteDomainBinding(context.Context, *DeleteDomainBindingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDomainBinding not implemented")
}
func (UnimplementedPlatformServiceServer) GetServiceStatus(context.Context, *GetServiceStatusRequest) (*ServiceStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceStatus not implemented")
}
func (UnimplementedPlatformServiceServer) ListServiceLogs(context.Context, *ListServiceLogsRequest) (*ListServiceLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServiceLogs not implemented")
}
func (UnimplementedPlatformServiceServer) ListServiceDeployments(context.Context, *ListServiceDeploymentsRequest) (*ListServiceDeploymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServiceDeployments not implemented")
}
func (UnimplementedPlatformServiceServer) ListAgents(context.Context, *emptypb.Empty) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedPlatformServiceServer) ListSandboxProfiles(context.Context, *emptypb.Empty) (*ListSandboxProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxProfiles not implemented")
}
func (UnimplementedPlatformServiceServer) mustEmbedUnimplementedPlatformServiceServer() {}
func (UnimplementedPlatformServiceServer) testEmbeddedByValue()                         {}

// UnsafePlatformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServiceServer will
// result in compilation errors.
type UnsafePlatformServiceServer interface {
	mustEmbedUnimplementedPlatformServiceServer()
}

func RegisterPlatformServiceServer(s grpc.ServiceRegistrar, srv PlatformServiceServer) {
	// If the following call panics, it indicates UnimplementedPlatformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformService_ServiceDesc, srv)
}

func _PlatformService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListProjects(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListEnvironments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvironmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListEnvironments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListEnvironments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListEnvironments(ctx, req.(*ListEnvironmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetEnvironment(ctx, req.(*GetEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_CreateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).CreateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_CreateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).CreateEnvironment(ctx, req.(*CreateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_DuplicateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DuplicateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DuplicateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DuplicateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DuplicateEnvironment(ctx, req.(*DuplicateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_RenameEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).RenameEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_RenameEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).RenameEnvironment(ctx, req.(*RenameEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_DeleteEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DeleteEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DeleteEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DeleteEnvironment(ctx, req.(*DeleteEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_DeployEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DeployEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DeployEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DeployEnvironment(ctx, req.(*DeployEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_LinkGitHubRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkGitHubRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).LinkGitHubRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_LinkGitHubRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).LinkGitHubRepository(ctx, req.(*LinkGitHubRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_InspectSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).InspectSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_InspectSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).InspectSource(ctx, req.(*InspectSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).UpdateService(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ScaleService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ScaleService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ScaleService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ScaleService(ctx, req.(*ScaleServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ApplyDeploymentAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDeploymentActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ApplyDeploymentAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ApplyDeploymentAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ApplyDeploymentAction(ctx, req.(*ApplyDeploymentActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_DiscardServiceChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardServiceChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DiscardServiceChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DiscardServiceChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DiscardServiceChanges(ctx, req.(*DiscardServiceChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DeleteService(ctx, req.(*DeleteServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DeleteVolume(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_CreateDomainBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).CreateDomainBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_CreateDomainBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).CreateDomainBinding(ctx, req.(*CreateDomainBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GenerateDomainBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDomainBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GenerateDomainBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GenerateDomainBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GenerateDomainBinding(ctx, req.(*GenerateDomainBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetDomainBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetDomainBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetDomainBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetDomainBinding(ctx, req.(*GetDomainBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListDomainBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListDomainBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListDomainBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListDomainBindings(ctx, req.(*ListDomainBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_UpdateDomainBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).UpdateDomainBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_UpdateDomainBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).UpdateDomainBinding(ctx, req.(*UpdateDomainBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_DeleteDomainBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DeleteDomainBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DeleteDomainBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DeleteDomainBinding(ctx, req.(*DeleteDomainBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetServiceStatus(ctx, req.(*GetServiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListServiceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListServiceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListServiceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListServiceLogs(ctx, req.(*ListServiceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListServiceDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceDeploymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListServiceDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListServiceDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListServiceDeployments(ctx, req.(*ListServiceDeploymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListAgents(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListSandboxProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListSandboxProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListSandboxProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListSandboxProfiles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformService_ServiceDesc is the grpc.ServiceDesc for PlatformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.v1.PlatformService",
	HandlerType: (*PlatformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _PlatformService_CreateProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _PlatformService_ListProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _PlatformService_GetProject_Handler,
		},
		{
			MethodName: "ListEnvironments",
			Handler:    _PlatformService_ListEnvironments_Handler,
		},
		{
			MethodName: "GetEnvironment",
			Handler:    _PlatformService_GetEnvironment_Handler,
		},
		{
			MethodName: "CreateEnvironment",
			Handler:    _PlatformService_CreateEnvironment_Handler,
		},
		{
			MethodName: "DuplicateEnvironment",
			Handler:    _PlatformService_DuplicateEnvironment_Handler,
		},
		{
			MethodName: "RenameEnvironment",
			Handler:    _PlatformService_RenameEnvironment_Handler,
		},
		{
			MethodName: "DeleteEnvironment",
			Handler:    _PlatformService_DeleteEnvironment_Handler,
		},
		{
			MethodName: "DeployEnvironment",
			Handler:    _PlatformService_DeployEnvironment_Handler,
		},
		{
			MethodName: "LinkGitHubRepository",
			Handler:    _PlatformService_LinkGitHubRepository_Handler,
		},
		{
			MethodName: "InspectSource",
			Handler:    _PlatformService_InspectSource_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _PlatformService_CreateService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _PlatformService_UpdateService_Handler,
		},
		{
			MethodName: "ScaleService",
			Handler:    _PlatformService_ScaleService_Handler,
		},
		{
			MethodName: "ApplyDeploymentAction",
			Handler:    _PlatformService_ApplyDeploymentAction_Handler,
		},
		{
			MethodName: "DiscardServiceChanges",
			Handler:    _PlatformService_DiscardServiceChanges_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _PlatformService_DeleteService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _PlatformService_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _PlatformService_ListServices_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _PlatformService_CreateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _PlatformService_DeleteVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _PlatformService_ListVolumes_Handler,
		},
		{
			MethodName: "CreateDomainBinding",
			Handler:    _PlatformService_CreateDomainBinding_Handler,
		},
		{
			MethodName: "GenerateDomainBinding",
			Handler:    _PlatformService_GenerateDomainBinding_Handler,
		},
		{
			MethodName: "GetDomainBinding",
			Handler:    _PlatformService_GetDomainBinding_Handler,
		},
		{
			MethodName: "ListDomainBindings",
			Handler:    _PlatformService_ListDomainBindings_Handler,
		},
		{
			MethodName: "UpdateDomainBinding",
			Handler:    _PlatformService_UpdateDomainBinding_Handler,
		},
		{
			MethodName: "DeleteDomainBinding",
			Handler:    _PlatformService_DeleteDomainBinding_Handler,
		},
		{
			MethodName: "GetServiceStatus",
			Handler:    _PlatformService_GetServiceStatus_Handler,
		},
		{
			MethodName: "ListServiceLogs",
			Handler:    _PlatformService_ListServiceLogs_Handler,
		},
		{
			MethodName: "ListServiceDeployments",
			Handler:    _PlatformService_ListServiceDeployments_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _PlatformService_ListAgents_Handler,
		},
		{
			MethodName: "ListSandboxProfiles",
			Handler:    _PlatformService_ListSandboxProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform.proto",
}

const (
	BuilderService_ClaimBuild_FullMethodName             = "/platform.v1.BuilderService/ClaimBuild"
	BuilderService_DownloadSourceSnapshot_FullMethodName = "/platform.v1.BuilderService/DownloadSourceSnapshot"
	BuilderService_ReportBuildHeartbeat_FullMethodName   = "/platform.v1.BuilderService/ReportBuildHeartbeat"
	BuilderService_ReportBuildLogs_FullMethodName        = "/platform.v1.BuilderService/ReportBuildLogs"
	BuilderService_CompleteBuild_FullMethodName          = "/platform.v1.BuilderService/CompleteBuild"
)

// BuilderServiceClient is the client API for BuilderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuilderServiceClient interface {
	ClaimBuild(ctx context.Context, in *ClaimBuildRequest, opts ...grpc.CallOption) (*BuildJob, error)
	DownloadSourceSnapshot(ctx context.Context, in *DownloadSourceSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SourceSnapshotChunk], error)
	ReportBuildHeartbeat(ctx context.Context, in *BuilderHeartbeatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReportBuildLogs(ctx context.Context, in *ReportBuildLogsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CompleteBuild(ctx context.Context, in *CompleteBuildRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type builderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuilderServiceClient(cc grpc.ClientConnInterface) BuilderServiceClient {
	return &builderServiceClient{cc}
}

func (c *builderServiceClient) ClaimBuild(ctx context.Context, in *ClaimBuildRequest, opts ...grpc.CallOption) (*BuildJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildJob)
	err := c.cc.Invoke(ctx, BuilderService_ClaimBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) DownloadSourceSnapshot(ctx context.Context, in *DownloadSourceSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SourceSnapshotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BuilderService_ServiceDesc.Streams[0], BuilderService_DownloadSourceSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadSourceSnapshotRequest, SourceSnapshotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuilderService_DownloadSourceSnapshotClient = grpc.ServerStreamingClient[SourceSnapshotChunk]

func (c *builderServiceClient) ReportBuildHeartbeat(ctx context.Context, in *BuilderHeartbeatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BuilderService_ReportBuildHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) ReportBuildLogs(ctx context.Context, in *ReportBuildLogsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BuilderService_ReportBuildLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *builderServiceClient) CompleteBuild(ctx context.Context, in *CompleteBuildRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BuilderService_CompleteBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuilderServiceServer is the server API for BuilderService service.
// All implementations must embed UnimplementedBuilderServiceServer
// for forward compatibility.
type BuilderServiceServer interface {
	ClaimBuild(context.Context, *ClaimBuildRequest) (*BuildJob, error)
	DownloadSourceSnapshot(*DownloadSourceSnapshotRequest, grpc.ServerStreamingServer[SourceSnapshotChunk]) error
	ReportBuildHeartbeat(context.Context, *BuilderHeartbeatRequest) (*emptypb.Empty, error)
	ReportBuildLogs(context.Context, *ReportBuildLogsRequest) (*emptypb.Empty, error)
	CompleteBuild(context.Context, *CompleteBuildRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBuilderServiceServer()
}

// UnimplementedBuilderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuilderServiceServer struct{}

func (UnimplementedBuilderServiceServer) ClaimBuild(context.Context, *ClaimBuildRequest) (*BuildJob, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimBuild not implemented")
}
func (UnimplementedBuilderServiceServer) DownloadSourceSnapshot(*DownloadSourceSnapshotRequest, grpc.ServerStreamingServer[SourceSnapshotChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadSourceSnapshot not implemented")
}
func (UnimplementedBuilderServiceServer) ReportBuildHeartbeat(context.Context, *BuilderHeartbeatRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportBuildHeartbeat not implemented")
}
func (UnimplementedBuilderServiceServer) ReportBuildLogs(context.Context, *ReportBuildLogsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportBuildLogs not implemented")
}
func (UnimplementedBuilderServiceServer) CompleteBuild(context.Context, *CompleteBuildRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteBuild not implemented")
}
func (UnimplementedBuilderServiceServer) mustEmbedUnimplementedBuilderServiceServer() {}
func (UnimplementedBuilderServiceServer) testEmbeddedByValue()                        {}

// UnsafeBuilderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuilderServiceServer will
// result in compilation errors.
type UnsafeBuilderServiceServer interface {
	mustEmbedUnimplementedBuilderServiceServer()
}

func RegisterBuilderServiceServer(s grpc.ServiceRegistrar, srv BuilderServiceServer) {
	// If the following call panics, it indicates UnimplementedBuilderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuilderService_ServiceDesc, srv)
}

func _BuilderService_ClaimBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).ClaimBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_ClaimBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).ClaimBuild(ctx, req.(*ClaimBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_DownloadSourceSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadSourceSnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BuilderServiceServer).DownloadSourceSnapshot(m, &grpc.GenericServerStream[DownloadSourceSnapshotRequest, SourceSnapshotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuilderService_DownloadSourceSnapshotServer = grpc.ServerStreamingServer[SourceSnapshotChunk]

func _BuilderService_ReportBuildHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuilderHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).ReportBuildHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_ReportBuildHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).ReportBuildHeartbeat(ctx, req.(*BuilderHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_ReportBuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportBuildLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).ReportBuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_ReportBuildLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).ReportBuildLogs(ctx, req.(*ReportBuildLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuilderService_CompleteBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuilderServiceServer).CompleteBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuilderService_CompleteBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuilderServiceServer).CompleteBuild(ctx, req.(*CompleteBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuilderService_ServiceDesc is the grpc.ServiceDesc for BuilderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuilderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.v1.BuilderService",
	HandlerType: (*BuilderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimBuild",
			Handler:    _BuilderService_ClaimBuild_Handler,
		},
		{
			MethodName: "ReportBuildHeartbeat",
			Handler:    _BuilderService_ReportBuildHeartbeat_Handler,
		},
		{
			MethodName: "ReportBuildLogs",
			Handler:    _BuilderService_ReportBuildLogs_Handler,
		},
		{
			MethodName: "CompleteBuild",
			Handler:    _BuilderService_CompleteBuild_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadSourceSnapshot",
			Handler:       _BuilderService_DownloadSourceSnapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "platform.proto",
}

const (
	OpsService_IngestGitHubWebhook_FullMethodName = "/platform.v1.OpsService/IngestGitHubWebhook"
	OpsService_ListFleet_FullMethodName           = "/platform.v1.OpsService/ListFleet"
	OpsService_CreateAgent_FullMethodName         = "/platform.v1.OpsService/CreateAgent"
	OpsService_UpdateAgent_FullMethodName         = "/platform.v1.OpsService/UpdateAgent"
	OpsService_SetAgentLifecycle_FullMethodName   = "/platform.v1.OpsService/SetAgentLifecycle"
)

// OpsServiceClient is the client API for OpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpsServiceClient interface {
	IngestGitHubWebhook(ctx context.Context, in *IngestGitHubWebhookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListFleet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Fleet, error)
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*AgentEnrollment, error)
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	SetAgentLifecycle(ctx context.Context, in *SetAgentLifecycleRequest, opts ...grpc.CallOption) (*Agent, error)
}

type opsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpsServiceClient(cc grpc.ClientConnInterface) OpsServiceClient {
	return &opsServiceClient{cc}
}

func (c *opsServiceClient) IngestGitHubWebhook(ctx context.Context, in *IngestGitHubWebhookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OpsService_IngestGitHubWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) ListFleet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Fleet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fleet)
	err := c.cc.Invoke(ctx, OpsService_ListFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*AgentEnrollment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentEnrollment)
	err := c.cc.Invoke(ctx, OpsService_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, OpsService_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsServiceClient) SetAgentLifecycle(ctx context.Context, in *SetAgentLifecycleRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, OpsService_SetAgentLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpsServiceServer is the server API for OpsService service.
// All implementations must embed UnimplementedOpsServiceServer
// for forward compatibility.
type OpsServiceServer interface {
	IngestGitHubWebhook(context.Context, *IngestGitHubWebhookRequest) (*emptypb.Empty, error)
	ListFleet(context.Context, *emptypb.Empty) (*Fleet, error)
	CreateAgent(context.Context, *CreateAgentRequest) (*AgentEnrollment, error)
	UpdateAgent(context.Context, *UpdateAgentRequest) (*Agent, error)
	SetAgentLifecycle(context.Context, *SetAgentLifecycleRequest) (*Agent, error)
	mustEmbedUnimplementedOpsServiceServer()
}

// UnimplementedOpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpsServiceServer struct{}

func (UnimplementedOpsServiceServer) IngestGitHubWebhook(context.Context, *IngestGitHubWebhookRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestGitHubWebhook not implemented")
}
func (UnimplementedOpsServiceServer) ListFleet(context.Context, *emptypb.Empty) (*Fleet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFleet not implemented")
}
func (UnimplementedOpsServiceServer) CreateAgent(context.Context, *CreateAgentRequest) (*AgentEnrollment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedOpsServiceServer) UpdateAgent(context.Context, *UpdateAgentRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedOpsServiceServer) SetAgentLifecycle(context.Context, *SetAgentLifecycleRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAgentLifecycle not implemented")
}
func (UnimplementedOpsServiceServer) mustEmbedUnimplementedOpsServiceServer() {}
func (UnimplementedOpsServiceServer) testEmbeddedByValue()                    {}

// UnsafeOpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpsServiceServer will
// result in compilation errors.
type UnsafeOpsServiceServer interface {
	mustEmbedUnimplementedOpsServiceServer()
}

func RegisterOpsServiceServer(s grpc.ServiceRegistrar, srv OpsServiceServer) {
	// If the following call panics, it indicates UnimplementedOpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpsService_ServiceDesc, srv)
}

func _OpsService_IngestGitHubWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestGitHubWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).IngestGitHubWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_IngestGitHubWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).IngestGitHubWebhook(ctx, req.(*IngestGitHubWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_ListFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).ListFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_ListFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).ListFleet(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsService_SetAgentLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAgentLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).SetAgentLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_SetAgentLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).SetAgentLifecycle(ctx, req.(*SetAgentLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpsService_ServiceDesc is the grpc.ServiceDesc for OpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.v1.OpsService",
	HandlerType: (*OpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestGitHubWebhook",
			Handler:    _OpsService_IngestGitHubWebhook_Handler,
		},
		{
			MethodName: "ListFleet",
			Handler:    _OpsService_ListFleet_Handler,
		},
		{
			MethodName: "CreateAgent",
			Handler:    _OpsService_CreateAgent_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _OpsService_UpdateAgent_Handler,
		},
		{
			MethodName: "SetAgentLifecycle",
			Handler:    _OpsService_SetAgentLifecycle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform.proto",
}
