/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as LivezRouteImport } from './routes/livez'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksGithubRouteImport } from './routes/webhooks/github'
import { Route as EventsServiceStatusRouteImport } from './routes/events/service-status'
import { Route as EventsProjectServicesRouteImport } from './routes/events/project-services'
import { Route as EventsEnvironmentServicesRouteImport } from './routes/events/environment-services'
import { Route as EnvironmentsEnvironmentIdRouteImport } from './routes/environments/$environmentId'
import { Route as AuthStartRouteImport } from './routes/auth/start'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const LivezRoute = LivezRouteImport.update({
  id: '/livez',
  path: '/livez',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksGithubRoute = WebhooksGithubRouteImport.update({
  id: '/webhooks/github',
  path: '/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsServiceStatusRoute = EventsServiceStatusRouteImport.update({
  id: '/events/service-status',
  path: '/events/service-status',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsProjectServicesRoute = EventsProjectServicesRouteImport.update({
  id: '/events/project-services',
  path: '/events/project-services',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEnvironmentServicesRoute =
  EventsEnvironmentServicesRouteImport.update({
    id: '/events/environment-services',
    path: '/events/environment-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnvironmentsEnvironmentIdRoute =
  EnvironmentsEnvironmentIdRouteImport.update({
    id: '/environments/$environmentId',
    path: '/environments/$environmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/auth/start',
  path: '/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/livez': typeof LivezRoute
  '/login': typeof LoginRoute
  '/fleet': typeof FleetRoute
  '/logout': typeof LogoutRoute
  '/readyz': typeof ReadyzRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/environments/$environmentId': typeof EnvironmentsEnvironmentIdRoute
  '/events/environment-services': typeof EventsEnvironmentServicesRoute
  '/events/project-services': typeof EventsProjectServicesRoute
  '/events/service-status': typeof EventsServiceStatusRoute
  '/webhooks/github': typeof WebhooksGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/livez': typeof LivezRoute
  '/login': typeof LoginRoute
  '/fleet': typeof FleetRoute
  '/logout': typeof LogoutRoute
  '/readyz': typeof ReadyzRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/environments/$environmentId': typeof EnvironmentsEnvironmentIdRoute
  '/events/environment-services': typeof EventsEnvironmentServicesRoute
  '/events/project-services': typeof EventsProjectServicesRoute
  '/events/service-status': typeof EventsServiceStatusRoute
  '/webhooks/github': typeof WebhooksGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/livez': typeof LivezRoute
  '/login': typeof LoginRoute
  '/fleet': typeof FleetRoute
  '/logout': typeof LogoutRoute
  '/readyz': typeof ReadyzRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/environments/$environmentId': typeof EnvironmentsEnvironmentIdRoute
  '/events/environment-services': typeof EventsEnvironmentServicesRoute
  '/events/project-services': typeof EventsProjectServicesRoute
  '/events/service-status': typeof EventsServiceStatusRoute
  '/webhooks/github': typeof WebhooksGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/livez'
    | '/login'
    | '/fleet'
    | '/logout'
    | '/readyz'
    | '/auth/callback'
    | '/auth/start'
    | '/environments/$environmentId'
    | '/events/environment-services'
    | '/events/project-services'
    | '/events/service-status'
    | '/webhooks/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/livez'
    | '/login'
    | '/fleet'
    | '/logout'
    | '/readyz'
    | '/auth/callback'
    | '/auth/start'
    | '/environments/$environmentId'
    | '/events/environment-services'
    | '/events/project-services'
    | '/events/service-status'
    | '/webhooks/github'
  id:
    | '__root__'
    | '/'
    | '/healthz'
    | '/livez'
    | '/login'
    | '/fleet'
    | '/logout'
    | '/readyz'
    | '/auth/callback'
    | '/auth/start'
    | '/environments/$environmentId'
    | '/events/environment-services'
    | '/events/project-services'
    | '/events/service-status'
    | '/webhooks/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthzRoute: typeof HealthzRoute
  LivezRoute: typeof LivezRoute
  LoginRoute: typeof LoginRoute
  FleetRoute: typeof FleetRoute
  LogoutRoute: typeof LogoutRoute
  ReadyzRoute: typeof ReadyzRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthStartRoute: typeof AuthStartRoute
  EnvironmentsEnvironmentIdRoute: typeof EnvironmentsEnvironmentIdRoute
  EventsEnvironmentServicesRoute: typeof EventsEnvironmentServicesRoute
  EventsProjectServicesRoute: typeof EventsProjectServicesRoute
  EventsServiceStatusRoute: typeof EventsServiceStatusRoute
  WebhooksGithubRoute: typeof WebhooksGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livez': {
      id: '/livez'
      path: '/livez'
      fullPath: '/livez'
      preLoaderRoute: typeof LivezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/github': {
      id: '/webhooks/github'
      path: '/webhooks/github'
      fullPath: '/webhooks/github'
      preLoaderRoute: typeof WebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/service-status': {
      id: '/events/service-status'
      path: '/events/service-status'
      fullPath: '/events/service-status'
      preLoaderRoute: typeof EventsServiceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/project-services': {
      id: '/events/project-services'
      path: '/events/project-services'
      fullPath: '/events/project-services'
      preLoaderRoute: typeof EventsProjectServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/environment-services': {
      id: '/events/environment-services'
      path: '/events/environment-services'
      fullPath: '/events/environment-services'
      preLoaderRoute: typeof EventsEnvironmentServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments/$environmentId': {
      id: '/environments/$environmentId'
      path: '/environments/$environmentId'
      fullPath: '/environments/$environmentId'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/start': {
      id: '/auth/start'
      path: '/auth/start'
      fullPath: '/auth/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthzRoute: HealthzRoute,
  LivezRoute: LivezRoute,
  LoginRoute: LoginRoute,
  FleetRoute: FleetRoute,
  LogoutRoute: LogoutRoute,
  ReadyzRoute: ReadyzRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthStartRoute: AuthStartRoute,
  EnvironmentsEnvironmentIdRoute: EnvironmentsEnvironmentIdRoute,
  EventsEnvironmentServicesRoute: EventsEnvironmentServicesRoute,
  EventsProjectServicesRoute: EventsProjectServicesRoute,
  EventsServiceStatusRoute: EventsServiceStatusRoute,
  WebhooksGithubRoute: WebhooksGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
