/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksGithubRouteImport } from './routes/webhooks/github'
import { Route as AuthStartRouteImport } from './routes/auth/start'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksGithubRoute = WebhooksGithubRouteImport.update({
  id: '/webhooks/github',
  path: '/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/auth/start',
  path: '/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/webhooks/github': typeof WebhooksGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/webhooks/github': typeof WebhooksGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/start': typeof AuthStartRoute
  '/webhooks/github': typeof WebhooksGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/auth/callback'
    | '/auth/start'
    | '/webhooks/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/auth/callback'
    | '/auth/start'
    | '/webhooks/github'
  id:
    | '__root__'
    | '/'
    | '/healthz'
    | '/login'
    | '/logout'
    | '/auth/callback'
    | '/auth/start'
    | '/webhooks/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthStartRoute: typeof AuthStartRoute
  WebhooksGithubRoute: typeof WebhooksGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/github': {
      id: '/webhooks/github'
      path: '/webhooks/github'
      fullPath: '/webhooks/github'
      preLoaderRoute: typeof WebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/start': {
      id: '/auth/start'
      path: '/auth/start'
      fullPath: '/auth/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthStartRoute: AuthStartRoute,
  WebhooksGithubRoute: WebhooksGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
