nodeName: node1
wireguard:
  interfaceName: wg0
  privateKey: "GDkp43RRm3PFDa7Ro1UULiYcnjlF/ucFebkXqS1jVmo="
  listenPort: 51820
  addresses:
    - 10.44.0.1/24
  peers:
    - name: node2
      publicKey: "k1fR/RyZ/P0y7EMoQMeP5B3rptgDqe52RXQbyxVMPgY="
      endpoint: "172.30.0.12:51820"
      allowedIPs:
        - 10.44.0.2/32
        - 172.31.0.0/24
      trustCIDRs:
        - 10.44.0.2/32
      persistentKeepaliveSeconds: 15
    - name: node3
      publicKey: "YV4ehQ6vE6mPXSmEEBfRRzMQyyVHykBBz6IcgbpKsEw="
      endpoint: "172.30.0.13:51820"
      allowedIPs:
        - 10.44.0.3/32
      trustCIDRs:
        - 10.44.0.3/32
      persistentKeepaliveSeconds: 15
firewall:
  conntrackEntries: 131072
  trustEntries: 8192
sync:
  enabled: true
  listen: "0.0.0.0:7001"
  authKey: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
  peers:
    - "172.30.0.12:7002"
    - "172.30.0.13:7003"
