// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	AgentControl_Enroll_FullMethodName                           = "/agent.v1.AgentControl/Enroll"
	AgentControl_IssueManagedDashboardCertificate_FullMethodName = "/agent.v1.AgentControl/IssueManagedDashboardCertificate"
	AgentControl_Sync_FullMethodName                             = "/agent.v1.AgentControl/Sync"
)

type AgentControlClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	IssueManagedDashboardCertificate(ctx context.Context, in *ManagedDashboardCertificateRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentClientMessage, AgentServerMessage], error)
}

type agentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlClient(cc grpc.ClientConnInterface) AgentControlClient {
	return &agentControlClient{cc}
}

func (c *agentControlClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, AgentControl_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) IssueManagedDashboardCertificate(ctx context.Context, in *ManagedDashboardCertificateRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, AgentControl_IssueManagedDashboardCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentClientMessage, AgentServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[0], AgentControl_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentClientMessage, AgentServerMessage]{ClientStream: stream}
	return x, nil
}

type AgentControl_SyncClient = grpc.BidiStreamingClient[AgentClientMessage, AgentServerMessage]

type AgentControlServer interface {
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	IssueManagedDashboardCertificate(context.Context, *ManagedDashboardCertificateRequest) (*EnrollResponse, error)
	Sync(grpc.BidiStreamingServer[AgentClientMessage, AgentServerMessage]) error
	mustEmbedUnimplementedAgentControlServer()
}

type UnimplementedAgentControlServer struct{}

func (UnimplementedAgentControlServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedAgentControlServer) IssueManagedDashboardCertificate(context.Context, *ManagedDashboardCertificateRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueManagedDashboardCertificate not implemented")
}
func (UnimplementedAgentControlServer) Sync(grpc.BidiStreamingServer[AgentClientMessage, AgentServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedAgentControlServer) mustEmbedUnimplementedAgentControlServer() {}
func (UnimplementedAgentControlServer) testEmbeddedByValue()                      {}

type UnsafeAgentControlServer interface {
	mustEmbedUnimplementedAgentControlServer()
}

func RegisterAgentControlServer(s grpc.ServiceRegistrar, srv AgentControlServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControl_ServiceDesc, srv)
}

func _AgentControl_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_IssueManagedDashboardCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagedDashboardCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).IssueManagedDashboardCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_IssueManagedDashboardCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).IssueManagedDashboardCertificate(ctx, req.(*ManagedDashboardCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServer).Sync(&grpc.GenericServerStream[AgentClientMessage, AgentServerMessage]{ServerStream: stream})
}

type AgentControl_SyncServer = grpc.BidiStreamingServer[AgentClientMessage, AgentServerMessage]

var AgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentControl",
	HandlerType: (*AgentControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _AgentControl_Enroll_Handler,
		},
		{
			MethodName: "IssueManagedDashboardCertificate",
			Handler:    _AgentControl_IssueManagedDashboardCertificate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _AgentControl_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
